using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Stats.Migrations
{
    public partial class Initial : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Players",
                columns: table => new
                {
                    PlayerId = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    Summoner = table.Column<string>(nullable: true),
                    Team = table.Column<string>(nullable: true),
                    Opponent = table.Column<string>(nullable: true),
                    Champion = table.Column<string>(nullable: true),
                    Role = table.Column<string>(nullable: true),
                    Kills = table.Column<int>(nullable: false),
                    Deaths = table.Column<int>(nullable: false),
                    Assists = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Players", x => x.PlayerId);
                });

            migrationBuilder.InsertData(
                table: "Players",
                columns: new[] { "PlayerId", "Assists", "Champion", "Deaths", "Kills", "Opponent", "Role", "Summoner", "Team" },
                values: new object[,]
                {
                    { 1, 7, "Caitlyn", 5, 14, "TAS", "ADC", "Theroclease", "GURL" },
                    { 287, 16, "Leona", 1, 2, "DD", "SUP", "Anh Bo Bùng Binh", "TAS" },
                    { 286, 15, "Thresh", 3, 0, "BBZ", "SUP", "Anh Bo Bùng Binh", "TAS" },
                    { 285, 13, "Alistar", 4, 0, "YUP", "SUP", "Anh Bo Bùng Binh", "TAS" },
                    { 284, 6, "Galio", 2, 1, "PTP", "SUP", "Anh Bo Bùng Binh", "TAS" },
                    { 283, 5, "Pantheon", 7, 1, "INT", "SUP", "Anh Bo Bùng Binh", "TAS" },
                    { 282, 10, "Galio", 4, 3, "GURL", "SUP", "Anh Bo Bùng Binh", "TAS" },
                    { 281, 9, "Kai'sa", 6, 16, "DD2", "ADC", "Gùa", "TAS" },
                    { 280, 7, "Yauso", 4, 10, "BBZ2", "ADC", "Gùa", "TAS" },
                    { 279, 11, "Tristina", 2, 14, "YUP2", "ADC", "Gùa", "TAS" },
                    { 278, 4, "Kalista", 6, 5, "INT2", "ADC", "Gùa", "TAS" },
                    { 288, 16, "Leona", 7, 4, "GURL2", "SUP", "Anh Bo Bùng Binh", "TAS" },
                    { 277, 11, "Lucian", 7, 8, "GURL2", "ADC", "Gùa", "TAS" },
                    { 275, 7, "Lucian", 3, 5, "BBZ", "ADC", "Gùa", "TAS" },
                    { 274, 1, "Yauso", 2, 5, "YUP", "ADC", "Gùa", "TAS" },
                    { 273, 4, "Tristina", 3, 1, "PTP", "ADC", "Gùa", "TAS" },
                    { 272, 6, "Lucian", 7, 3, "INT", "ADC", "Gùa", "TAS" },
                    { 271, 6, "Lucian", 4, 9, "GURL", "ADC", "Gùa", "TAS" },
                    { 270, 5, "Oriana", 3, 8, "YUP2", "MID", "Hismee", "TAS" },
                    { 269, 6, "Sejuani", 3, 3, "PTP2", "JNG", "Hismee", "TAS" },
                    { 268, 15, "Malzhar", 6, 6, "GURL2", "MID", "Hismee", "TAS" },
                    { 267, 9, "Shyvana", 1, 6, "BBZ", "JNG", "Hismee", "TAS" },
                    { 266, 10, "Oriana", 1, 6, "YUP", "MID", "Hismee", "TAS" },
                    { 276, 13, "Tristina", 2, 5, "DD", "ADC", "Gùa", "TAS" },
                    { 265, 10, "Malphite", 1, 0, "PTP", "MID", "Hismee", "TAS" },
                    { 289, 10, "Thresh", 5, 1, "INT2", "SUP", "Anh Bo Bùng Binh", "TAS" },
                    { 291, 13, "Alistar", 2, 0, "YUP2", "SUP", "Anh Bo Bùng Binh", "TAS" },
                    { 313, 7, "Poppy", 5, 2, "DD", "TOP", "UltMilesMorales", "YUP" },
                    { 312, 3, "Nasus", 3, 1, "BBZ2", "TOP", "SmoothMoves", "YUP" },
                    { 311, 2, "illoai", 7, 3, "TAS2", "TOP", "SmoothMoves", "YUP" },
                    { 310, 3, "Shen", 6, 0, "PTP2", "TOP", "SmoothMoves", "YUP" },
                    { 309, 3, "Shen", 6, 0, "INT2", "TOP", "SmoothMoves", "YUP" },
                    { 308, 7, "Yorick", 9, 2, "GURL2", "TOP", "SmoothMoves", "YUP" },
                    { 307, 1, "Yorick", 1, 0, "DD2", "TOP", "SmoothMoves", "YUP" },
                    { 306, 1, "Yorick", 8, 3, "BBZ", "TOP", "SmoothMoves", "YUP" },
                    { 305, 5, "Shen", 4, 0, "TAS", "TOP", "SmoothMoves", "YUP" },
                    { 304, 10, "Nami", 6, 1, "PTP", "SUP", "SmoothMoves", "YUP" },
                    { 290, 7, "Soraka", 5, 1, "PTP2", "SUP", "Anh Bo Bùng Binh", "TAS" },
                    { 303, 1, "Janna", 3, 0, "INT", "SUP", "SmoothMoves", "YUP" },
                    { 301, 15, "Lulu", 5, 1, "DD", "SUP", "SmoothMoves", "YUP" },
                    { 300, 14, "Ryze", 5, 8, "DD2", "MID", "Trash Zero", "TAS" },
                    { 299, 9, "Kayle", 5, 1, "BBZ2", "MID", "Trash Zero", "TAS" },
                    { 298, 3, "Vladamir", 3, 3, "PTP2", "MID", "Trash Zero", "TAS" },
                    { 297, 6, "Jax", 5, 4, "INT2", "JNG", "Trash Zero", "TAS" },
                    { 296, 5, "Kayn", 2, 9, "DD", "JNG", "Trash Zero", "TAS" },
                    { 295, 8, "Zac", 5, 2, "GURL", "JNG", "Voltox", "TAS" },
                    { 294, 9, "Master-yi", 8, 8, "GURL", "JNG", "Voltox", "TAS" },
                    { 293, 19, "Swain", 5, 3, "DD2", "SUP", "Anh Bo Bùng Binh", "TAS" },
                    { 292, 17, "Blitzcrank", 5, 1, "BBZ2", "SUP", "Anh Bo Bùng Binh", "TAS" },
                    { 302, 21, "Lulu", 3, 1, "GURL", "SUP", "SmoothMoves", "YUP" },
                    { 264, 3, "Oriana", 7, 2, "INT", "MID", "Hismee", "TAS" },
                    { 263, 7, "Neeko", 4, 4, "GURL", "MID", "Hismee", "TAS" },
                    { 262, 19, "Poppy", 6, 2, "DD2", "JNG", "Yoniee", "TAS" },
                    { 234, 8, "Braum", 3, 1, "BBZ2", "SUP", "Karrots", "PTP" },
                    { 233, 12, "Thresh", 2, 0, "YUP2", "SUP", "Karrots", "PTP" },
                    { 232, 8, "Morgana", 3, 0, "TAS2", "SUP", "Karrots", "PTP" },
                    { 231, 9, "Thresh", 2, 3, "INT2", "SUP", "Karrots", "PTP" },
                    { 230, 15, "Thresh", 2, 4, "GURL", "SUP", "Karrots", "PTP" },
                    { 229, 15, "Leona", 2, 3, "DD", "SUP", "Karrots", "PTP" },
                    { 228, 23, "Leona", 4, 0, "BBZ", "SUP", "Karrots", "PTP" },
                    { 227, 18, "Morgana", 2, 3, "YUP", "SUP", "Karrots", "PTP" },
                    { 226, 5, "Blitzcrank", 3, 3, "TAS", "SUP", "Karrots", "PTP" },
                    { 225, 4, "Leona", 3, 0, "INT", "SUP", "Karrots", "PTP" },
                    { 235, 6, "Malzahar", 2, 4, "DD2", "MID", "Karrots", "PTP" },
                    { 224, 7, "Tristina", 2, 9, "GURL2", "ADC", "Lets-Do-Väynäl", "PTP" },
                    { 222, 7, "Ahpilios", 3, 6, "BBZ2", "ADC", "Lets-Do-Väynäl", "PTP" },
                    { 221, 5, "Vayne", 1, 5, "YUP2", "ADC", "Lets-Do-Väynäl", "PTP" },
                    { 220, 8, "Senna", 4, 1, "TAS2", "ADC", "Lets-Do-Väynäl", "PTP" },
                    { 219, 4, "Vayne", 2, 5, "INT2", "ADC", "Lets-Do-Väynäl", "PTP" },
                    { 218, 12, "Vayne", 3, 4, "GURL", "ADC", "Lets-Do-Väynäl", "PTP" },
                    { 217, 9, "Twitch", 7, 6, "DD", "ADC", "Lets-Do-Väynäl", "PTP" },
                    { 216, 10, "Jhin", 2, 7, "YUP", "ADC", "Lets-Do-Väynäl", "PTP" },
                    { 215, 3, "Jinx", 4, 3, "TAS", "ADC", "Lets-Do-Väynäl", "PTP" },
                    { 214, 4, "Jhin", 4, 1, "INT", "ADC", "Lets-Do-Väynäl", "PTP" },
                    { 213, 13, "Oriana", 2, 6, "GURL2", "MID", "TheProDH", "PTP" },
                    { 223, 9, "Jinx", 3, 6, "DD2", "ADC", "Lets-Do-Väynäl", "PTP" },
                    { 236, 16, "Thresh", 2, 0, "GURL2", "SUP", "Karrots", "PTP" },
                    { 237, 3, "Graves", 7, 4, "INT", "JNG", "TooMuchDamage", "PTP" },
                    { 238, 16, "Maoki", 3, 1, "YUP", "TOP", "FA7HOM", "PTP" },
                    { 261, 13, "Shyvana", 2, 7, "BBZ2", "JNG", "Yoniee", "TAS" },
                    { 260, 10, "Gragas", 1, 4, "YUP2", "JNG", "Yoniee", "TAS" },
                    { 259, 6, "Ezreal", 5, 1, "PTP2", "ADC", "Yoniee", "TAS" },
                    { 258, 5, "Vladamir", 5, 2, "INT2", "MID", "Yoniee", "TAS" },
                    { 257, 12, "Fiddlesticks", 6, 7, "GURL2", "JNG", "Yoniee", "TAS" },
                    { 256, 3, "Twisted-fate", 1, 9, "DD", "MID", "Yoniee", "TAS" },
                    { 255, 8, "Oriana", 2, 7, "BBZ", "MID", "Yoniee", "TAS" },
                    { 254, 7, "Kha'zix", 1, 4, "YUP", "JNG", "Yoniee", "TAS" },
                    { 253, 5, "Kha'zix", 2, 13, "PTP", "JNG", "Yoniee", "TAS" },
                    { 252, 6, "Sett", 2, 6, "DD2", "TOP", "Strawberryyy", "TAS" },
                    { 251, 7, "Aatrox", 3, 3, "BBZ2", "TOP", "Strawberryyy", "TAS" },
                    { 250, 9, "Gnar", 2, 2, "YUP2", "TOP", "Strawberryyy", "TAS" },
                    { 249, 3, "Jayce", 6, 4, "PTP2", "TOP", "Strawberryyy", "TAS" },
                    { 248, 8, "Wu-kong", 5, 6, "INT2", "TOP", "Strawberryyy", "TAS" },
                    { 247, 10, "Wu-kong", 2, 11, "GURL2", "TOP", "Strawberryyy", "TAS" },
                    { 246, 9, "Wu-kong", 0, 7, "DD", "TOP", "Strawberryyy", "TAS" },
                    { 245, 4, "Renekton", 2, 7, "BBZ", "TOP", "Strawberryyy", "TAS" },
                    { 244, 8, "Kennan", 2, 5, "YUP", "TOP", "Strawberryyy", "TAS" },
                    { 243, 3, "Renekton", 1, 8, "PTP", "TOP", "Strawberryyy", "TAS" },
                    { 242, 1, "Akali", 5, 3, "INT", "TOP", "Strawberryyy", "TAS" },
                    { 241, 10, "Camile", 5, 3, "GURL", "TOP", "Strawberryyy", "TAS" },
                    { 240, 10, "Thresh", 3, 3, "DD2", "SUP", "FleshIsAPrision", "PTP" },
                    { 239, 17, "Ammumu", 2, 7, "BBZ", "JNG", "GreyHawk31", "PTP" },
                    { 314, 10, "Gnar", 6, 1, "GURL", "TOP", "UltMilesMorales", "YUP" },
                    { 212, 15, "Lilah", 0, 9, "BBZ2", "MID", "TheProDH", "PTP" },
                    { 315, 0, "Neeko", 2, 1, "INT", "MID", "UltMilesMorales", "YUP" },
                    { 317, 1, "Ekko", 4, 4, "TAS", "MID", "Connection-Error", "YUP" },
                    { 392, 1, "Kayle", 3, 3, "BBZ", "TOP", "Lyhtz", "DD" },
                    { 391, 10, "Vladamir", 5, 6, "YUP", "MID", "Lyhtz", "DD" },
                    { 390, 11, "Jhin", 5, 6, "TAS2", "ADC", "Epic-Gaymes", "DD" },
                    { 389, 2, "Jhin", 5, 1, "PTP2", "ADC", "Epic-Gaymes", "DD" },
                    { 388, 12, "Jhin", 2, 9, "GURL2", "ADC", "Epic-Gaymes", "DD" },
                    { 387, 5, "Jhin", 5, 2, "BBZ2", "ADC", "Epic-Gaymes", "DD" },
                    { 386, 2, "Olaf", 5, 0, "YUP2", "JNG", "Epic-Gaymes", "DD" },
                    { 385, 5, "Hecraim", 6, 0, "TAS", "JNG", "Epic-Gaymes", "DD" },
                    { 384, 12, "Hecraim", 6, 3, "PTP", "JNG", "Epic-Gaymes", "DD" },
                    { 383, 6, "Hecraim", 5, 3, "GURL", "JNG", "Epic-Gaymes", "DD" },
                    { 393, 4, "Jinx", 7, 8, "GURL", "ADC", "Lyhtz", "DD" },
                    { 382, 10, "Kha'zix", 3, 1, "BBZ", "JNG", "Epic-Gaymes", "DD" },
                    { 380, 16, "Alistar", 10, 1, "TAS2", "SUP", "6EtHaNoS9", "DD" },
                    { 379, 8, "Galio", 4, 1, "PTP2", "SUP", "6EtHaNoS9", "DD" },
                    { 378, 3, "Alistar", 6, 0, "INT2", "SUP", "6EtHaNoS9", "DD" },
                    { 377, 19, "Alistar", 2, 1, "GURL2", "SUP", "6EtHaNoS9", "DD" },
                    { 376, 3, "Leona", 7, 0, "BBZ2", "SUP", "6EtHaNoS9", "DD" },
                    { 375, 0, "Morgana", 3, 0, "YUP2", "SUP", "6EtHaNoS9", "DD" },
                    { 374, 3, "Nautalis", 5, 1, "TAS", "SUP", "6EtHaNoS9", "DD" },
                    { 373, 16, "Rakan", 5, 1, "PTP", "SUP", "6EtHaNoS9", "DD" },
                    { 372, 22, "Leona", 9, 1, "INT", "SUP", "6EtHaNoS9", "DD" },
                    { 371, 8, "Nautalis", 9, 0, "GURL", "SUP", "6EtHaNoS9", "DD" },
                    { 381, 10, "Olaf", 6, 1, "YUP", "JNG", "Epic-Gaymes", "DD" },
                    { 370, 1, "Lulu", 4, 0, "BBZ", "SUP", "6EtHaNoS9", "DD" },
                    { 394, 11, "Jinx", 6, 14, "INT", "ADC", "Lyhtz", "DD" },
                    { 396, 3, "Jinx", 6, 2, "TAS", "ADC", "Lyhtz", "DD" },
                    { 418, 2, "Kassadin", 10, 3, "TAS", "MID", "DD-ON-TOP-XDDDDD", "DD" },
                    { 417, 9, "Vladamir", 4, 11, "PTP", "MID", "DD-ON-TOP-XDDDDD", "DD" },
                    { 416, 16, "Vladamir", 4, 8, "INT", "MID", "DD-ON-TOP-XDDDDD", "DD" },
                    { 415, 9, "Kassadin", 4, 4, "GURL", "MID", "DD-ON-TOP-XDDDDD", "DD" },
                    { 414, 1, "Ashe", 3, 1, "BBZ", "ADC", "DD-ON-TOP-XDDDDD", "DD" },
                    { 413, 5, "Caitlyn", 4, 15, "YUP", "ADC", "DD-ON-TOP-XDDDDD", "DD" },
                    { 412, 9, "Rumble", 6, 10, "TAS2", "MID", "Smaafu", "DD" },
                    { 411, 8, "Rumble", 2, 4, "PTP2", "MID", "Smaafu", "DD" },
                    { 410, 6, "Oriana", 4, 4, "INT2", "MID", "Smaafu", "DD" },
                    { 409, 12, "Rumble", 3, 7, "GURL2", "MID", "Smaafu", "DD" },
                    { 395, 11, "Xayah", 3, 6, "PTP", "ADC", "Lyhtz", "DD" },
                    { 408, 3, "Vi", 8, 0, "BBZ2", "JNG", "Smaafu", "DD" },
                    { 406, 9, "Mordakaiser", 4, 5, "PTP", "TOP", "Smaafu", "DD" },
                    { 405, 13, "Yorick", 5, 11, "INT", "TOP", "Smaafu", "DD" },
                    { 404, 6, "Dr.Mundo", 7, 1, "GURL", "TOP", "Smaafu", "DD" },
                    { 403, 3, "Galio", 2, 0, "BBZ", "MID", "Smaafu", "DD" },
                    { 402, 11, "Kayn", 7, 4, "TAS2", "JNG", "Lyhtz", "DD" },
                    { 401, 5, "Kayn", 5, 9, "PTP2", "JNG", "Lyhtz", "DD" },
                    { 400, 6, "Kayn", 5, 7, "INT2", "JNG", "Lyhtz", "DD" },
                    { 399, 13, "Hecraim", 3, 11, "GURL2", "JNG", "Lyhtz", "DD" },
                    { 398, 2, "Vladamir", 4, 4, "BBZ2", "MID", "Lyhtz", "DD" },
                    { 397, 1, "Ashe", 3, 1, "YUP2", "ADC", "Lyhtz", "DD" },
                    { 407, 2, "Fiora", 5, 0, "TAS", "TOP", "Smaafu", "DD" },
                    { 369, 16, "Morgana", 4, 2, "YUP", "SUP", "6EtHaNoS9", "DD" },
                    { 368, 11, "Shen", 7, 3, "TAS2", "TOP", "Teaamoe", "DD" },
                    { 367, 8, "Shen", 3, 0, "DD2", "TOP", "Teaamoe", "DD" },
                    { 339, 1, "Lux", 3, 5, "PTP2", "MID", "5picy1cey", "YUP" },
                    { 338, 11, "Lissandra", 6, 9, "GURL2", "MID", "5picy1cey", "YUP" },
                    { 337, 6, "Leona", 3, 1, "TAS", "SUP", "5picy1cey", "YUP" },
                    { 336, 4, "Lissandra", 9, 2, "PTP", "TOP", "5picy1cey", "YUP" },
                    { 335, 1, "Mordakaiser", 6, 0, "INT", "TOP", "5picy1cey", "YUP" },
                    { 334, 12, "Elise", 5, 7, "GURL", "JNG", "5picy1cey", "YUP" },
                    { 333, 11, "Diana", 7, 5, "DD", "JNG", "5picy1cey", "YUP" },
                    { 332, 5, "Olaf", 5, 2, "BBZ2", "JNG", "OnceWeak", "YUP" },
                    { 331, 2, "Sett", 5, 0, "INT2", "JNG", "OnceWeak", "YUP" },
                    { 330, 12, "Hecraim", 5, 3, "GURL2", "JNG", "OnceWeak", "YUP" },
                    { 340, 3, "Zyra", 4, 2, "TAS2", "SUP", "5picy1cey", "YUP" },
                    { 329, 8, "Hecraim", 1, 4, "DD2", "JNG", "OnceWeak", "YUP" },
                    { 327, 5, "Ashe", 4, 1, "TAS", "ADC", "OnceWeak", "YUP" },
                    { 326, 10, "Olaf", 7, 5, "PTP", "JNG", "OnceWeak", "YUP" },
                    { 325, 0, "Sejuani", 3, 0, "INT", "JNG", "OnceWeak", "YUP" },
                    { 324, 11, "Galio", 9, 3, "GURL", "MID", "OnceWeak", "YUP" },
                    { 323, 11, "Oriana", 4, 3, "DD", "MID", "OnceWeak", "YUP" },
                    { 322, 4, "Morgana", 5, 1, "PTP2", "SUP", "Connection-Error", "YUP" },
                    { 321, 3, "Yummi", 3, 0, "INT2", "SUP", "Connection-Error", "YUP" },
                    { 320, 23, "Yummi", 4, 1, "GURL2", "SUP", "Connection-Error", "YUP" },
                    { 319, 11, "Yummi", 0, 0, "DD2", "SUP", "Connection-Error", "YUP" },
                    { 318, 10, "Yummi", 4, 1, "BBZ", "SUP", "Connection-Error", "YUP" },
                    { 328, 11, "Jarvan-IV", 4, 0, "BBZ", "JNG", "OnceWeak", "YUP" },
                    { 341, 12, "Zilean", 2, 1, "BBZ2", "SUP", "5picy1cey", "YUP" },
                    { 342, 10, "Varus", 4, 11, "GURL", "ADC", "XTurtleOfDoomX", "YUP" },
                    { 343, 0, "Sivir", 3, 0, "INT", "ADC", "XTurtleOfDoomX", "YUP" },
                    { 366, 7, "Shen", 1, 2, "INT2", "TOP", "Teaamoe", "DD" },
                    { 365, 17, "Shen", 2, 3, "GURL2", "TOP", "Teaamoe", "DD" },
                    { 364, 2, "Urgot", 5, 3, "BBZ2", "TOP", "Teaamoe", "DD" },
                    { 363, 0, "Shen", 2, 2, "YUP2", "TOP", "Teaamoe", "DD" },
                    { 362, 9, "Dr.Mundo", 3, 5, "YUP", "TOP", "Teaamoe", "DD" },
                    { 361, 13, "Kayn", 8, 6, "INT", "JNG", "LPelican", "DD" },
                    { 360, 3, "Sett", 4, 0, "TAS2", "JNG", "Savedbytheaj", "YUP" },
                    { 359, 2, "Lee-sin", 5, 4, "TAS", "JNG", "Savedbytheaj", "YUP" },
                    { 358, 6, "Akali", 5, 5, "PTP", "MID", "Savedbytheaj", "YUP" },
                    { 357, 3, "Ekko", 5, 8, "BBZ", "MID", "EliteStrike", "YUP" },
                    { 356, 5, "Akali", 2, 7, "BBZ2", "MID", "EliteStrike", "YUP" },
                    { 355, 4, "Ekko", 8, 3, "TAS2", "MID", "EliteStrike", "YUP" },
                    { 354, 1, "Azir", 3, 2, "INT2", "MID", "EliteStrike", "YUP" },
                    { 353, 7, "Ekko", 1, 8, "DD2", "MID", "EliteStrike", "YUP" },
                    { 352, 3, "Ekko", 5, 8, "BBZ", "MID", "EliteStrike", "YUP" },
                    { 351, 7, "Ashe", 1, 5, "BBZ2", "ADC", "XTurtleOfDoomX", "YUP" },
                    { 350, 5, "Ashe", 5, 2, "TAS2", "ADC", "XTurtleOfDoomX", "YUP" },
                    { 349, 2, "Lucian", 5, 1, "PTP2", "ADC", "XTurtleOfDoomX", "YUP" },
                    { 348, 1, "Caitlyn", 3, 2, "INT2", "ADC", "XTurtleOfDoomX", "YUP" },
                    { 347, 10, "Ashe", 4, 14, "GURL2", "ADC", "XTurtleOfDoomX", "YUP" },
                    { 346, 4, "Caitlyn", 0, 4, "DD2", "ADC", "XTurtleOfDoomX", "YUP" },
                    { 345, 3, "Caitlyn", 1, 7, "BBZ", "ADC", "XTurtleOfDoomX", "YUP" },
                    { 344, 7, "Ashe", 5, 5, "PTP", "ADC", "XTurtleOfDoomX", "YUP" },
                    { 316, 5, "Tristina", 8, 11, "DD", "ADC", "Connection-Error", "YUP" },
                    { 211, 5, "Veigar", 1, 12, "YUP2", "MID", "TheProDH", "PTP" },
                    { 210, 5, "Malzahar", 0, 6, "TAS2", "MID", "TheProDH", "PTP" },
                    { 209, 11, "Lilah", 2, 12, "INT2", "MID", "TheProDH", "PTP" },
                    { 76, 19, "Hecraim", 1, 1, "DD2", "JNG", "Rârgh", "BBZ" },
                    { 75, 6, "Veigar", 5, 3, "YUP", "MID", "Rârgh", "BBZ" },
                    { 74, 3, "Galio", 8, 3, "TAS", "SUP", "Rârgh", "BBZ" },
                    { 73, 3, "Sejuani", 8, 2, "INT", "JNG", "Rârgh", "BBZ" },
                    { 72, 13, "Sejuani", 6, 7, "GURL", "JNG", "Rârgh", "BBZ" },
                    { 71, 8, "Hecraim", 2, 1, "DD", "JNG", "Rârgh", "BBZ" },
                    { 70, 6, "Mordakaiser", 2, 5, "YUP2", "TOP", "ShieldedValor", "BBZ" },
                    { 69, 11, "Rumble", 2, 4, "TAS2", "TOP", "ShieldedValor", "BBZ" },
                    { 68, 4, "Sylas", 4, 3, "PTP2", "TOP", "ShieldedValor", "BBZ" },
                    { 67, 10, "Rumble", 1, 2, "INT2", "TOP", "ShieldedValor", "BBZ" },
                    { 77, 14, "Hecraim", 3, 3, "GURL2", "JNG", "Rârgh", "BBZ" },
                    { 66, 9, "Shen", 0, 4, "GURL2", "TOP", "ShieldedValor", "BBZ" },
                    { 64, 1, "Jax", 3, 10, "YUP", "TOP", "ShieldedValor", "BBZ" },
                    { 63, 5, "Ornn", 4, 1, "TAS", "TOP", "ShieldedValor", "BBZ" },
                    { 62, 6, "Riven", 5, 4, "PTP", "TOP", "ShieldedValor", "BBZ" },
                    { 61, 2, "Maoki", 5, 1, "INT", "TOP", "ShieldedValor", "BBZ" },
                    { 60, 5, "Tahm Kench", 5, 0, "PTP2", "SUP", "Unburdened", "GURL" },
                    { 59, 1, "Leona", 6, 0, "INT2", "SUP", "Unburdened", "GURL" },
                    { 58, 8, "Nami", 3, 0, "DD2", "SUP", "Warlock-Herald", "GURL" },
                    { 57, 3, "Hecraim", 7, 3, "PTP2", "JNG", "Truelax21", "GURL" },
                    { 56, 2, "Trundle", 7, 3, "INT2", "JNG", "Truelax21", "GURL" },
                    { 55, 4, "Ashe", 5, 4, "DD2", "ADC", "Truelax21", "GURL" }
                });

            migrationBuilder.InsertData(
                table: "Players",
                columns: new[] { "PlayerId", "Assists", "Champion", "Deaths", "Kills", "Opponent", "Role", "Summoner", "Team" },
                values: new object[,]
                {
                    { 65, 18, "Shen", 1, 4, "DD2", "TOP", "ShieldedValor", "BBZ" },
                    { 54, 7, "Senna", 5, 3, "BBZ", "SUP", "Vale-Claddath", "GURL" },
                    { 78, 2, "Zac", 5, 0, "INT2", "JNG", "Rârgh", "BBZ" },
                    { 80, 11, "Hecraim", 4, 2, "TAS2", "JNG", "Rârgh", "BBZ" },
                    { 102, 11, "Lulu", 3, 0, "YUP", "SUP", "Luciferalfa", "BBZ" },
                    { 101, 7, "Senna", 2, 1, "TAS", "SUP", "Luciferalfa", "BBZ" },
                    { 100, 6, "Nautalis", 9, 2, "PTP", "SUP", "Luciferalfa", "BBZ" },
                    { 99, 3, "Morgana", 6, 0, "INT", "SUP", "Luciferalfa", "BBZ" },
                    { 98, 12, "Sona", 1, 3, "GURL", "SUP", "Luciferalfa", "BBZ" },
                    { 97, 12, "Morgana", 0, 0, "DD", "SUP", "Luciferalfa", "BBZ" },
                    { 96, 3, "Miss-fortune", 3, 7, "PTP2", "ADC", "Ssunrise", "BBZ" },
                    { 95, 3, "Kai'sa", 3, 0, "INT2", "ADC", "Ssunrise", "BBZ" },
                    { 94, 5, "Kai'sa", 1, 14, "GURL2", "ADC", "Ssunrise", "BBZ" },
                    { 93, 10, "Kai'sa", 1, 14, "DD2", "ADC", "Ssunrise", "BBZ" },
                    { 79, 10, "Sejuani", 10, 0, "PTP2", "JNG", "Rârgh", "BBZ" },
                    { 92, 7, "Kog'Maw", 4, 5, "YUP", "ADC", "Ssunrise", "BBZ" },
                    { 90, 4, "Kindred", 5, 6, "PTP", "JNG", "Ssunrise", "BBZ" },
                    { 89, 2, "Caitlyn", 3, 1, "INT", "ADC", "Ssunrise", "BBZ" },
                    { 88, 21, "Lux", 2, 2, "GURL", "ADC", "Ssunrise", "BBZ" },
                    { 87, 10, "Caitlyn", 1, 7, "DD", "ADC", "Ssunrise", "BBZ" },
                    { 86, 5, "Viktor", 2, 1, "YUP2", "MID", "Huebs", "BBZ" },
                    { 85, 10, "Azir", 4, 4, "TAS2", "MID", "Huebs", "BBZ" },
                    { 84, 8, "Yone", 6, 3, "PTP2", "MID", "Huebs", "BBZ" },
                    { 83, 0, "Yauso", 5, 1, "INT2", "MID", "Huebs", "BBZ" },
                    { 82, 7, "Yone", 5, 5, "GURL", "MID", "Huebs", "BBZ" },
                    { 81, 5, "Jarvan-IV", 5, 1, "YUP2", "JNG", "Rârgh", "BBZ" },
                    { 91, 4, "Kindred", 7, 4, "TAS", "JNG", "Ssunrise", "BBZ" },
                    { 53, 14, "Thresh", 9, 0, "TAS", "SUP", "Vale-Claddath", "GURL" },
                    { 52, 14, "Graves", 3, 3, "TAS", "JNG", "TyrantKingTyrone", "GURL" },
                    { 51, 0, "Xayah", 5, 1, "BBZ2", "ADC", "Mr-Turbo-Int", "GURL" },
                    { 23, 14, "Warwick", 10, 1, "YUP", "JNG", "Willow233", "GURL" },
                    { 22, 3, "Mordakaiser", 4, 3, "TAS", "TOP", "Willow233", "GURL" },
                    { 21, 5, "Kled", 7, 3, "PTP2", "TOP", "BakinPancakes", "GURL" },
                    { 20, 2, "Poppy", 6, 1, "INT2", "TOP", "BakinPancakes", "GURL" },
                    { 19, 4, "Urgot", 7, 3, "DD2", "TOP", "BakinPancakes", "GURL" },
                    { 18, 3, "Urgot", 5, 2, "BBZ2", "TOP", "BakinPancakes", "GURL" },
                    { 17, 8, "Urgot", 4, 13, "YUP2", "TOP", "BakinPancakes", "GURL" },
                    { 16, 9, "Mordakaiser", 7, 7, "TAS2", "TOP", "BakinPancakes", "GURL" },
                    { 15, 8, "Kled", 6, 6, "PTP", "TOP", "BakinPancakes", "GURL" },
                    { 14, 1, "Mordakaiser", 4, 3, "INT", "TOP", "BakinPancakes", "GURL" },
                    { 24, 11, "Skarner", 3, 2, "BBZ", "JNG", "Willow233", "GURL" },
                    { 13, 10, "Mordakaiser", 4, 11, "DD", "TOP", "BakinPancakes", "GURL" },
                    { 11, 11, "Urgot", 2, 7, "YUP", "TOP", "BakinPancakes", "GURL" },
                    { 10, 2, "Caitlyn", 5, 3, "PTP2", "ADC", "Theroclease", "GURL" },
                    { 9, 0, "Ashe", 7, 2, "INT2", "ADC", "Theroclease", "GURL" },
                    { 8, 0, "Pyke", 6, 1, "BBZ2", "SUP", "Theroclease", "GURL" },
                    { 7, 17, "Morgana", 7, 3, "YUP2", "SUP", "Theroclease", "GURL" },
                    { 6, 15, "Thresh", 4, 1, "TAS2", "SUP", "Theroclease", "GURL" },
                    { 5, 11, "Lucian", 7, 3, "PTP", "ADC", "Theroclease", "GURL" },
                    { 4, 3, "Tristina", 4, 7, "INT", "ADC", "Theroclease", "GURL" },
                    { 3, 12, "Ezreal", 1, 11, "DD", "ADC", "Theroclease", "GURL" },
                    { 2, 8, "Jinx", 2, 15, "YUP", "ADC", "Theroclease", "GURL" },
                    { 12, 3, "Kled", 6, 3, "BBZ", "TOP", "BakinPancakes", "GURL" },
                    { 25, 20, "Ammumu", 4, 4, "DD", "JNG", "Willow233", "GURL" },
                    { 26, 4, "Skarner", 5, 2, "INT", "JNG", "Willow233", "GURL" },
                    { 27, 5, "Nocturne", 9, 6, "PTP", "JNG", "Willow233", "GURL" },
                    { 50, 9, "Ezreal", 6, 6, "YUP2", "ADC", "Mr-Turbo-Int", "GURL" },
                    { 49, 12, "Ashe", 8, 4, "TAS2", "ADC", "Mr-Turbo-Int", "GURL" },
                    { 48, 11, "Leona", 9, 0, "PTP", "SUP", "Mr-Turbo-Int", "GURL" },
                    { 47, 8, "Leona", 7, 0, "INT", "SUP", "Mr-Turbo-Int", "GURL" },
                    { 46, 10, "Lux", 3, 2, "DD", "SUP", "Mr-Turbo-Int", "GURL" },
                    { 45, 7, "Jinx", 6, 0, "BBZ", "ADC", "Mr-Turbo-Int", "GURL" },
                    { 44, 5, "Pyke", 6, 1, "YUP", "SUP", "Mr-Turbo-Int", "GURL" },
                    { 43, 6, "Malzahar", 4, 3, "PTP2", "MID", "XNek0X", "GURL" },
                    { 42, 0, "Annie", 3, 1, "INT2", "MID", "XNek0X", "GURL" },
                    { 41, 4, "Malzahar", 6, 3, "DD2", "MID", "XNek0X", "GURL" },
                    { 40, 3, "Veigar", 5, 2, "BBZ2", "MID", "XNek0X", "GURL" },
                    { 39, 9, "Le-Blanc", 4, 3, "YUP2", "MID", "XNek0X", "GURL" },
                    { 38, 7, "Lissandra", 8, 12, "TAS2", "MID", "XNek0X", "GURL" },
                    { 37, 3, "Brand", 5, 3, "PTP", "MID", "XNek0X", "GURL" },
                    { 36, 4, "Malzahar", 3, 0, "INT", "MID", "XNek0X", "GURL" },
                    { 35, 11, "Brand", 4, 4, "DD", "MID", "XNek0X", "GURL" },
                    { 34, 2, "Lissandra", 5, 10, "BBZ", "MID", "XNek0X", "GURL" },
                    { 33, 17, "Morgana", 4, 3, "YUP", "MID", "XNek0X", "GURL" },
                    { 32, 12, "Malzahar", 6, 4, "TAS", "MID", "XNek0X", "GURL" },
                    { 31, 7, "Nocturne", 10, 0, "DD2", "JNG", "Willow233", "GURL" },
                    { 30, 3, "Nunu", 4, 1, "BBZ2", "JNG", "Willow233", "GURL" },
                    { 29, 15, "Nunu", 8, 3, "YUP2", "JNG", "Willow233", "GURL" },
                    { 28, 13, "Hecraim", 9, 4, "TAS2", "JNG", "Willow233", "GURL" },
                    { 103, 17, "Galio", 2, 2, "DD2", "SUP", "Luciferalfa", "BBZ" },
                    { 104, 12, "Galio", 1, 1, "GURL2", "SUP", "Luciferalfa", "BBZ" },
                    { 105, 2, "Galio", 7, 0, "INT2", "SUP", "Luciferalfa", "BBZ" },
                    { 106, 3, "Leona", 6, 1, "PTP2", "SUP", "Luciferalfa", "BBZ" },
                    { 181, 3, "Kennan", 4, 0, "TAS", "TOP", "Pure Llama", "PTP" },
                    { 180, 4, "Sylas", 1, 3, "GURL", "TOP", "fishfishmagish", "INT" },
                    { 179, 14, "Renekton", 8, 7, "DD", "TOP", "fishfishmagish", "INT" },
                    { 178, 18, "Zilean", 0, 0, "GURL2", "SUP", "HeWhoSlopps", "INT" },
                    { 177, 14, "Nautalis", 3, 0, "DD2", "SUP", "HeWhoSlopps", "INT" },
                    { 176, 16, "Zilean", 0, 3, "BBZ2", "SUP", "HeWhoSlopps", "INT" },
                    { 175, 14, "Zilean", 0, 2, "YUP2", "SUP", "HeWhoSlopps", "INT" },
                    { 174, 12, "Nautalis", 3, 4, "TAS2", "SUP", "HeWhoSlopps", "INT" },
                    { 173, 4, "Nautalis", 6, 2, "PTP2", "SUP", "HeWhoSlopps", "INT" },
                    { 172, 12, "Nautalis", 3, 0, "GURL", "SUP", "HeWhoSlopps", "INT" },
                    { 182, 10, "Malphite", 1, 7, "BBZ", "TOP", "Pure Llama", "PTP" },
                    { 171, 21, "Fiddlesticks", 9, 2, "DD", "SUP", "HeWhoSlopps", "INT" },
                    { 169, 9, "Nautalis", 0, 3, "YUP", "SUP", "HeWhoSlopps", "INT" },
                    { 168, 19, "Nautalis", 3, 2, "TAS", "SUP", "HeWhoSlopps", "INT" },
                    { 167, 15, "Nautalis", 3, 2, "PTP", "SUP", "HeWhoSlopps", "INT" },
                    { 166, 3, "Jhin", 1, 5, "GURL2", "ADC", "KennyHammerspike", "INT" },
                    { 165, 9, "Vayne", 1, 6, "DD2", "ADC", "KennyHammerspike", "INT" },
                    { 164, 7, "Vayne", 1, 11, "BBZ2", "ADC", "KennyHammerspike", "INT" },
                    { 163, 10, "Miss-fortune", 1, 5, "YUP2", "ADC", "KennyHammerspike", "INT" },
                    { 162, 12, "Caitlyn", 4, 5, "TAS2", "ADC", "KennyHammerspike", "INT" },
                    { 161, 4, "Ezreal", 5, 2, "PTP2", "ADC", "KennyHammerspike", "INT" },
                    { 160, 4, "Ezreal", 2, 11, "GURL", "ADC", "KennyHammerspike", "INT" },
                    { 170, 8, "Braum", 2, 2, "BBZ", "SUP", "HeWhoSlopps", "INT" },
                    { 183, 12, "Malphite", 4, 3, "DD", "TOP", "Pure Llama", "PTP" },
                    { 184, 3, "Darius", 5, 9, "GURL", "TOP", "Pure Llama", "PTP" },
                    { 185, 14, "Maoki", 0, 3, "INT2", "TOP", "Pure Llama", "PTP" },
                    { 208, 9, "Lilah", 3, 14, "GURL", "MID", "TheProDH", "PTP" },
                    { 207, 10, "Viktor", 4, 7, "DD", "MID", "TheProDH", "PTP" },
                    { 206, 17, "Lilah", 2, 8, "BBZ", "MID", "TheProDH", "PTP" },
                    { 205, 8, "Brand", 6, 13, "YUP", "MID", "TheProDH", "PTP" },
                    { 204, 3, "Viktor", 5, 0, "TAS", "MID", "TheProDH", "PTP" },
                    { 203, 3, "Malzahar", 4, 2, "INT", "MID", "TheProDH", "PTP" },
                    { 202, 14, "Sejuani", 3, 8, "GURL2", "JNG", "Graviel", "PTP" },
                    { 201, 11, "Hecraim", 4, 2, "DD2", "JNG", "Graviel", "PTP" },
                    { 200, 18, "Hecraim", 6, 6, "BBZ2", "JNG", "Graviel", "PTP" },
                    { 199, 6, "Kayn", 2, 2, "YUP2", "JNG", "Graviel", "PTP" },
                    { 198, 7, "Hecraim", 2, 9, "TAS2", "JNG", "Graviel", "PTP" },
                    { 197, 14, "Kayn", 4, 6, "INT2", "JNG", "Graviel", "PTP" },
                    { 196, 18, "Hecraim", 5, 5, "GURL", "JNG", "Graviel", "PTP" },
                    { 195, 15, "Shen", 9, 3, "DD", "JNG", "Graviel", "PTP" },
                    { 194, 16, "Ashe", 4, 10, "BBZ", "ADC", "Graviel", "PTP" },
                    { 193, 15, "Nocturne", 5, 8, "YUP", "JNG", "Graviel", "PTP" },
                    { 192, 1, "Zac", 7, 3, "TAS", "JNG", "Graviel", "PTP" },
                    { 191, 5, "Renekton", 7, 1, "INT", "TOP", "Graviel", "PTP" },
                    { 190, 5, "Teemo", 3, 5, "GURL2", "TOP", "Pure Llama", "PTP" },
                    { 189, 6, "Mordakaiser", 3, 4, "DD2", "TOP", "Pure Llama", "PTP" },
                    { 188, 13, "Maoki", 3, 7, "BBZ2", "TOP", "Pure Llama", "PTP" },
                    { 187, 4, "Ornn", 2, 4, "YUP2", "TOP", "Pure Llama", "PTP" },
                    { 186, 8, "Maoki", 3, 6, "TAS2", "TOP", "Pure Llama", "PTP" },
                    { 159, 8, "Heimerdinger", 6, 13, "DD", "ADC", "KennyHammerspike", "INT" },
                    { 419, 1, "Anniva", 3, 0, "YUP2", "MID", "DD-ON-TOP-XDDDDD", "DD" },
                    { 158, 10, "Ezreal", 1, 5, "BBZ", "ADC", "KennyHammerspike", "INT" },
                    { 156, 13, "Ezreal", 3, 10, "TAS", "ADC", "KennyHammerspike", "INT" },
                    { 128, 10, "Camile", 4, 6, "TAS2", "TOP", "Brocklee900", "INT" },
                    { 127, 2, "Shen", 4, 2, "PTP2", "TOP", "Brocklee900", "INT" },
                    { 126, 6, "Ekko", 1, 3, "GURL", "MID", "Brocklee900", "INT" },
                    { 125, 14, "Camile", 6, 8, "DD", "MID", "Brocklee900", "INT" },
                    { 124, 15, "Shen", 1, 3, "BBZ", "TOP", "Brocklee900", "INT" },
                    { 123, 9, "Shen", 0, 1, "YUP", "TOP", "Brocklee900", "INT" },
                    { 122, 7, "Camile", 1, 9, "TAS", "TOP", "Brocklee900", "INT" },
                    { 121, 10, "Camile", 2, 5, "PTP", "TOP", "Brocklee900", "INT" },
                    { 120, 4, "Varus", 7, 1, "PTP", "ADC", "Abhi Kris", "BBZ" },
                    { 119, 0, "Kai'sa", 3, 6, "TUP2", "ADC", "Chris-Sunga", "BBZ" },
                    { 129, 1, "Mordakaiser", 1, 8, "YUP2", "TOP", "Brocklee900", "INT" },
                    { 118, 8, "Lucian", 3, 8, "TAS2", "ADC", "Chris-Sunga", "BBZ" },
                    { 116, 12, "Azir", 4, 8, "DD2", "MID", "Chris-Sunga", "BBZ" },
                    { 115, 9, "Lee-sin", 4, 4, "YUP", "JNG", "Chris-Sunga", "BBZ" },
                    { 114, 3, "Le-Blanc", 4, 2, "TAS", "MID", "Chris-Sunga", "BBZ" },
                    { 113, 7, "Galio", 6, 0, "PTP", "MID", "Chris-Sunga", "BBZ" },
                    { 112, 3, "Syndra", 3, 2, "INT", "MID", "Chris-Sunga", "BBZ" },
                    { 111, 8, "Oriana", 1, 2, "DD", "MID", "Chris-Sunga", "BBZ" },
                    { 110, 9, "Gnar", 4, 8, "GURL", "TOP", "AllMightTheHero", "BBZ" },
                    { 109, 7, "Gnar", 1, 5, "DD", "TOP", "AllMightTheHero", "BBZ" },
                    { 108, 5, "Shen", 4, 0, "YUP2", "SUP", "Luciferalfa", "BBZ" },
                    { 107, 14, "Braum", 9, 1, "TAS2", "SUP", "Luciferalfa", "BBZ" },
                    { 117, 7, "Zilean", 2, 3, "GURL2", "MID", "Chris-Sunga", "BBZ" },
                    { 130, 10, "Shen", 0, 1, "BBZ2", "TOP", "Brocklee900", "INT" },
                    { 131, 7, "Camile", 4, 5, "DD2", "TOP", "Brocklee900", "INT" },
                    { 132, 9, "Vi", 2, 11, "GURL2", "JNG", "Brocklee900", "INT" },
                    { 155, 10, "Caitlyn", 1, 9, "PTP", "ADC", "KennyHammerspike", "INT" },
                    { 154, 5, "Cassiopia", 2, 6, "GURL2", "TOP", "Evolvednewb", "INT" },
                    { 153, 7, "Viktor", 1, 6, "DD2", "MID", "Evolvednewb", "INT" },
                    { 152, 11, "Syndra", 0, 6, "BBZ2", "MID", "Evolvednewb", "INT" },
                    { 151, 13, "Viktor", 0, 2, "YUP2", "MID", "Evolvednewb", "INT" },
                    { 150, 10, "Syndra", 3, 3, "TAS2", "MID", "Evolvednewb", "INT" },
                    { 149, 5, "Ziggs", 6, 2, "PTP2", "MID", "Evolvednewb", "INT" },
                    { 148, 10, "Azir", 0, 5, "BBZ", "MID", "Evolvednewb", "INT" },
                    { 147, 10, "Ziggs", 0, 2, "YUP", "MID", "Evolvednewb", "INT" },
                    { 146, 14, "Viktor", 3, 5, "TAS", "MID", "Evolvednewb", "INT" },
                    { 145, 11, "Oriana", 1, 3, "PTP", "MID", "Evolvednewb", "INT" },
                    { 144, 14, "Katarina", 2, 7, "GURL2", "MID", "BoExplode87", "INT" },
                    { 143, 15, "Sejuani", 5, 3, "DD2", "JNG", "BoExplode87", "INT" },
                    { 142, 14, "Sejuani", 2, 3, "BBZ2", "JNG", "BoExplode87", "INT" },
                    { 141, 14, "Sejuani", 2, 3, "YUP2", "JNG", "BoExplode87", "INT" },
                    { 140, 15, "Sejuani", 4, 8, "TAS2", "JNG", "BoExplode87", "INT" },
                    { 139, 4, "Ekko", 8, 0, "PTP2", "JNG", "BoExplode87", "INT" },
                    { 138, 9, "Olaf", 5, 6, "GURL", "JNG", "BoExplode87", "INT" },
                    { 137, 18, "Lee-sin", 11, 2, "DD", "JNG", "BoExplode87", "INT" },
                    { 136, 13, "Olaf", 2, 10, "BBZ", "JNG", "BoExplode87", "INT" },
                    { 135, 13, "Trundle", 0, 3, "YUP", "JNG", "BoExplode87", "INT" },
                    { 134, 22, "Volibear", 1, 5, "TAS", "JNG", "BoExplode87", "INT" },
                    { 133, 14, "Volibear", 1, 6, "PTP", "JNG", "BoExplode87", "INT" },
                    { 157, 4, "Caitlyn", 1, 8, "YUP", "ADC", "KennyHammerspike", "INT" },
                    { 420, 3, "Jhin", 4, 1, "INT2", "ADC", "Epic-Gaymes", "DD" }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Players");
        }
    }
}
