// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stats.Models;

namespace Stats.Migrations
{
    [DbContext(typeof(StatsContext))]
    [Migration("20201002205826_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Stats.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Assists");

                    b.Property<string>("Champion");

                    b.Property<int>("Deaths");

                    b.Property<int>("Kills");

                    b.Property<string>("Opponent");

                    b.Property<string>("Role");

                    b.Property<string>("Summoner");

                    b.Property<string>("Team");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            Assists = 7,
                            Champion = "Caitlyn",
                            Deaths = 5,
                            Kills = 14,
                            Opponent = "TAS",
                            Role = "ADC",
                            Summoner = "Theroclease",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 2,
                            Assists = 8,
                            Champion = "Jinx",
                            Deaths = 2,
                            Kills = 15,
                            Opponent = "YUP",
                            Role = "ADC",
                            Summoner = "Theroclease",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 3,
                            Assists = 12,
                            Champion = "Ezreal",
                            Deaths = 1,
                            Kills = 11,
                            Opponent = "DD",
                            Role = "ADC",
                            Summoner = "Theroclease",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 4,
                            Assists = 3,
                            Champion = "Tristina",
                            Deaths = 4,
                            Kills = 7,
                            Opponent = "INT",
                            Role = "ADC",
                            Summoner = "Theroclease",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 5,
                            Assists = 11,
                            Champion = "Lucian",
                            Deaths = 7,
                            Kills = 3,
                            Opponent = "PTP",
                            Role = "ADC",
                            Summoner = "Theroclease",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 6,
                            Assists = 15,
                            Champion = "Thresh",
                            Deaths = 4,
                            Kills = 1,
                            Opponent = "TAS2",
                            Role = "SUP",
                            Summoner = "Theroclease",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 7,
                            Assists = 17,
                            Champion = "Morgana",
                            Deaths = 7,
                            Kills = 3,
                            Opponent = "YUP2",
                            Role = "SUP",
                            Summoner = "Theroclease",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 8,
                            Assists = 0,
                            Champion = "Pyke",
                            Deaths = 6,
                            Kills = 1,
                            Opponent = "BBZ2",
                            Role = "SUP",
                            Summoner = "Theroclease",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 9,
                            Assists = 0,
                            Champion = "Ashe",
                            Deaths = 7,
                            Kills = 2,
                            Opponent = "INT2",
                            Role = "ADC",
                            Summoner = "Theroclease",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 10,
                            Assists = 2,
                            Champion = "Caitlyn",
                            Deaths = 5,
                            Kills = 3,
                            Opponent = "PTP2",
                            Role = "ADC",
                            Summoner = "Theroclease",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 11,
                            Assists = 11,
                            Champion = "Urgot",
                            Deaths = 2,
                            Kills = 7,
                            Opponent = "YUP",
                            Role = "TOP",
                            Summoner = "BakinPancakes",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 12,
                            Assists = 3,
                            Champion = "Kled",
                            Deaths = 6,
                            Kills = 3,
                            Opponent = "BBZ",
                            Role = "TOP",
                            Summoner = "BakinPancakes",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 13,
                            Assists = 10,
                            Champion = "Mordakaiser",
                            Deaths = 4,
                            Kills = 11,
                            Opponent = "DD",
                            Role = "TOP",
                            Summoner = "BakinPancakes",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 14,
                            Assists = 1,
                            Champion = "Mordakaiser",
                            Deaths = 4,
                            Kills = 3,
                            Opponent = "INT",
                            Role = "TOP",
                            Summoner = "BakinPancakes",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 15,
                            Assists = 8,
                            Champion = "Kled",
                            Deaths = 6,
                            Kills = 6,
                            Opponent = "PTP",
                            Role = "TOP",
                            Summoner = "BakinPancakes",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 16,
                            Assists = 9,
                            Champion = "Mordakaiser",
                            Deaths = 7,
                            Kills = 7,
                            Opponent = "TAS2",
                            Role = "TOP",
                            Summoner = "BakinPancakes",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 17,
                            Assists = 8,
                            Champion = "Urgot",
                            Deaths = 4,
                            Kills = 13,
                            Opponent = "YUP2",
                            Role = "TOP",
                            Summoner = "BakinPancakes",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 18,
                            Assists = 3,
                            Champion = "Urgot",
                            Deaths = 5,
                            Kills = 2,
                            Opponent = "BBZ2",
                            Role = "TOP",
                            Summoner = "BakinPancakes",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 19,
                            Assists = 4,
                            Champion = "Urgot",
                            Deaths = 7,
                            Kills = 3,
                            Opponent = "DD2",
                            Role = "TOP",
                            Summoner = "BakinPancakes",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 20,
                            Assists = 2,
                            Champion = "Poppy",
                            Deaths = 6,
                            Kills = 1,
                            Opponent = "INT2",
                            Role = "TOP",
                            Summoner = "BakinPancakes",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 21,
                            Assists = 5,
                            Champion = "Kled",
                            Deaths = 7,
                            Kills = 3,
                            Opponent = "PTP2",
                            Role = "TOP",
                            Summoner = "BakinPancakes",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 22,
                            Assists = 3,
                            Champion = "Mordakaiser",
                            Deaths = 4,
                            Kills = 3,
                            Opponent = "TAS",
                            Role = "TOP",
                            Summoner = "Willow233",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 23,
                            Assists = 14,
                            Champion = "Warwick",
                            Deaths = 10,
                            Kills = 1,
                            Opponent = "YUP",
                            Role = "JNG",
                            Summoner = "Willow233",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 24,
                            Assists = 11,
                            Champion = "Skarner",
                            Deaths = 3,
                            Kills = 2,
                            Opponent = "BBZ",
                            Role = "JNG",
                            Summoner = "Willow233",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 25,
                            Assists = 20,
                            Champion = "Ammumu",
                            Deaths = 4,
                            Kills = 4,
                            Opponent = "DD",
                            Role = "JNG",
                            Summoner = "Willow233",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 26,
                            Assists = 4,
                            Champion = "Skarner",
                            Deaths = 5,
                            Kills = 2,
                            Opponent = "INT",
                            Role = "JNG",
                            Summoner = "Willow233",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 27,
                            Assists = 5,
                            Champion = "Nocturne",
                            Deaths = 9,
                            Kills = 6,
                            Opponent = "PTP",
                            Role = "JNG",
                            Summoner = "Willow233",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 28,
                            Assists = 13,
                            Champion = "Hecraim",
                            Deaths = 9,
                            Kills = 4,
                            Opponent = "TAS2",
                            Role = "JNG",
                            Summoner = "Willow233",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 29,
                            Assists = 15,
                            Champion = "Nunu",
                            Deaths = 8,
                            Kills = 3,
                            Opponent = "YUP2",
                            Role = "JNG",
                            Summoner = "Willow233",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 30,
                            Assists = 3,
                            Champion = "Nunu",
                            Deaths = 4,
                            Kills = 1,
                            Opponent = "BBZ2",
                            Role = "JNG",
                            Summoner = "Willow233",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 31,
                            Assists = 7,
                            Champion = "Nocturne",
                            Deaths = 10,
                            Kills = 0,
                            Opponent = "DD2",
                            Role = "JNG",
                            Summoner = "Willow233",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 32,
                            Assists = 12,
                            Champion = "Malzahar",
                            Deaths = 6,
                            Kills = 4,
                            Opponent = "TAS",
                            Role = "MID",
                            Summoner = "XNek0X",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 33,
                            Assists = 17,
                            Champion = "Morgana",
                            Deaths = 4,
                            Kills = 3,
                            Opponent = "YUP",
                            Role = "MID",
                            Summoner = "XNek0X",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 34,
                            Assists = 2,
                            Champion = "Lissandra",
                            Deaths = 5,
                            Kills = 10,
                            Opponent = "BBZ",
                            Role = "MID",
                            Summoner = "XNek0X",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 35,
                            Assists = 11,
                            Champion = "Brand",
                            Deaths = 4,
                            Kills = 4,
                            Opponent = "DD",
                            Role = "MID",
                            Summoner = "XNek0X",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 36,
                            Assists = 4,
                            Champion = "Malzahar",
                            Deaths = 3,
                            Kills = 0,
                            Opponent = "INT",
                            Role = "MID",
                            Summoner = "XNek0X",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 37,
                            Assists = 3,
                            Champion = "Brand",
                            Deaths = 5,
                            Kills = 3,
                            Opponent = "PTP",
                            Role = "MID",
                            Summoner = "XNek0X",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 38,
                            Assists = 7,
                            Champion = "Lissandra",
                            Deaths = 8,
                            Kills = 12,
                            Opponent = "TAS2",
                            Role = "MID",
                            Summoner = "XNek0X",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 39,
                            Assists = 9,
                            Champion = "Le-Blanc",
                            Deaths = 4,
                            Kills = 3,
                            Opponent = "YUP2",
                            Role = "MID",
                            Summoner = "XNek0X",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 40,
                            Assists = 3,
                            Champion = "Veigar",
                            Deaths = 5,
                            Kills = 2,
                            Opponent = "BBZ2",
                            Role = "MID",
                            Summoner = "XNek0X",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 41,
                            Assists = 4,
                            Champion = "Malzahar",
                            Deaths = 6,
                            Kills = 3,
                            Opponent = "DD2",
                            Role = "MID",
                            Summoner = "XNek0X",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 42,
                            Assists = 0,
                            Champion = "Annie",
                            Deaths = 3,
                            Kills = 1,
                            Opponent = "INT2",
                            Role = "MID",
                            Summoner = "XNek0X",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 43,
                            Assists = 6,
                            Champion = "Malzahar",
                            Deaths = 4,
                            Kills = 3,
                            Opponent = "PTP2",
                            Role = "MID",
                            Summoner = "XNek0X",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 44,
                            Assists = 5,
                            Champion = "Pyke",
                            Deaths = 6,
                            Kills = 1,
                            Opponent = "YUP",
                            Role = "SUP",
                            Summoner = "Mr-Turbo-Int",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 45,
                            Assists = 7,
                            Champion = "Jinx",
                            Deaths = 6,
                            Kills = 0,
                            Opponent = "BBZ",
                            Role = "ADC",
                            Summoner = "Mr-Turbo-Int",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 46,
                            Assists = 10,
                            Champion = "Lux",
                            Deaths = 3,
                            Kills = 2,
                            Opponent = "DD",
                            Role = "SUP",
                            Summoner = "Mr-Turbo-Int",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 47,
                            Assists = 8,
                            Champion = "Leona",
                            Deaths = 7,
                            Kills = 0,
                            Opponent = "INT",
                            Role = "SUP",
                            Summoner = "Mr-Turbo-Int",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 48,
                            Assists = 11,
                            Champion = "Leona",
                            Deaths = 9,
                            Kills = 0,
                            Opponent = "PTP",
                            Role = "SUP",
                            Summoner = "Mr-Turbo-Int",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 49,
                            Assists = 12,
                            Champion = "Ashe",
                            Deaths = 8,
                            Kills = 4,
                            Opponent = "TAS2",
                            Role = "ADC",
                            Summoner = "Mr-Turbo-Int",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 50,
                            Assists = 9,
                            Champion = "Ezreal",
                            Deaths = 6,
                            Kills = 6,
                            Opponent = "YUP2",
                            Role = "ADC",
                            Summoner = "Mr-Turbo-Int",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 51,
                            Assists = 0,
                            Champion = "Xayah",
                            Deaths = 5,
                            Kills = 1,
                            Opponent = "BBZ2",
                            Role = "ADC",
                            Summoner = "Mr-Turbo-Int",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 52,
                            Assists = 14,
                            Champion = "Graves",
                            Deaths = 3,
                            Kills = 3,
                            Opponent = "TAS",
                            Role = "JNG",
                            Summoner = "TyrantKingTyrone",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 53,
                            Assists = 14,
                            Champion = "Thresh",
                            Deaths = 9,
                            Kills = 0,
                            Opponent = "TAS",
                            Role = "SUP",
                            Summoner = "Vale-Claddath",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 54,
                            Assists = 7,
                            Champion = "Senna",
                            Deaths = 5,
                            Kills = 3,
                            Opponent = "BBZ",
                            Role = "SUP",
                            Summoner = "Vale-Claddath",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 55,
                            Assists = 4,
                            Champion = "Ashe",
                            Deaths = 5,
                            Kills = 4,
                            Opponent = "DD2",
                            Role = "ADC",
                            Summoner = "Truelax21",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 56,
                            Assists = 2,
                            Champion = "Trundle",
                            Deaths = 7,
                            Kills = 3,
                            Opponent = "INT2",
                            Role = "JNG",
                            Summoner = "Truelax21",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 57,
                            Assists = 3,
                            Champion = "Hecraim",
                            Deaths = 7,
                            Kills = 3,
                            Opponent = "PTP2",
                            Role = "JNG",
                            Summoner = "Truelax21",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 58,
                            Assists = 8,
                            Champion = "Nami",
                            Deaths = 3,
                            Kills = 0,
                            Opponent = "DD2",
                            Role = "SUP",
                            Summoner = "Warlock-Herald",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 59,
                            Assists = 1,
                            Champion = "Leona",
                            Deaths = 6,
                            Kills = 0,
                            Opponent = "INT2",
                            Role = "SUP",
                            Summoner = "Unburdened",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 60,
                            Assists = 5,
                            Champion = "Tahm Kench",
                            Deaths = 5,
                            Kills = 0,
                            Opponent = "PTP2",
                            Role = "SUP",
                            Summoner = "Unburdened",
                            Team = "GURL"
                        },
                        new
                        {
                            PlayerId = 61,
                            Assists = 2,
                            Champion = "Maoki",
                            Deaths = 5,
                            Kills = 1,
                            Opponent = "INT",
                            Role = "TOP",
                            Summoner = "ShieldedValor",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 62,
                            Assists = 6,
                            Champion = "Riven",
                            Deaths = 5,
                            Kills = 4,
                            Opponent = "PTP",
                            Role = "TOP",
                            Summoner = "ShieldedValor",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 63,
                            Assists = 5,
                            Champion = "Ornn",
                            Deaths = 4,
                            Kills = 1,
                            Opponent = "TAS",
                            Role = "TOP",
                            Summoner = "ShieldedValor",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 64,
                            Assists = 1,
                            Champion = "Jax",
                            Deaths = 3,
                            Kills = 10,
                            Opponent = "YUP",
                            Role = "TOP",
                            Summoner = "ShieldedValor",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 65,
                            Assists = 18,
                            Champion = "Shen",
                            Deaths = 1,
                            Kills = 4,
                            Opponent = "DD2",
                            Role = "TOP",
                            Summoner = "ShieldedValor",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 66,
                            Assists = 9,
                            Champion = "Shen",
                            Deaths = 0,
                            Kills = 4,
                            Opponent = "GURL2",
                            Role = "TOP",
                            Summoner = "ShieldedValor",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 67,
                            Assists = 10,
                            Champion = "Rumble",
                            Deaths = 1,
                            Kills = 2,
                            Opponent = "INT2",
                            Role = "TOP",
                            Summoner = "ShieldedValor",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 68,
                            Assists = 4,
                            Champion = "Sylas",
                            Deaths = 4,
                            Kills = 3,
                            Opponent = "PTP2",
                            Role = "TOP",
                            Summoner = "ShieldedValor",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 69,
                            Assists = 11,
                            Champion = "Rumble",
                            Deaths = 2,
                            Kills = 4,
                            Opponent = "TAS2",
                            Role = "TOP",
                            Summoner = "ShieldedValor",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 70,
                            Assists = 6,
                            Champion = "Mordakaiser",
                            Deaths = 2,
                            Kills = 5,
                            Opponent = "YUP2",
                            Role = "TOP",
                            Summoner = "ShieldedValor",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 71,
                            Assists = 8,
                            Champion = "Hecraim",
                            Deaths = 2,
                            Kills = 1,
                            Opponent = "DD",
                            Role = "JNG",
                            Summoner = "Rârgh",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 72,
                            Assists = 13,
                            Champion = "Sejuani",
                            Deaths = 6,
                            Kills = 7,
                            Opponent = "GURL",
                            Role = "JNG",
                            Summoner = "Rârgh",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 73,
                            Assists = 3,
                            Champion = "Sejuani",
                            Deaths = 8,
                            Kills = 2,
                            Opponent = "INT",
                            Role = "JNG",
                            Summoner = "Rârgh",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 74,
                            Assists = 3,
                            Champion = "Galio",
                            Deaths = 8,
                            Kills = 3,
                            Opponent = "TAS",
                            Role = "SUP",
                            Summoner = "Rârgh",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 75,
                            Assists = 6,
                            Champion = "Veigar",
                            Deaths = 5,
                            Kills = 3,
                            Opponent = "YUP",
                            Role = "MID",
                            Summoner = "Rârgh",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 76,
                            Assists = 19,
                            Champion = "Hecraim",
                            Deaths = 1,
                            Kills = 1,
                            Opponent = "DD2",
                            Role = "JNG",
                            Summoner = "Rârgh",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 77,
                            Assists = 14,
                            Champion = "Hecraim",
                            Deaths = 3,
                            Kills = 3,
                            Opponent = "GURL2",
                            Role = "JNG",
                            Summoner = "Rârgh",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 78,
                            Assists = 2,
                            Champion = "Zac",
                            Deaths = 5,
                            Kills = 0,
                            Opponent = "INT2",
                            Role = "JNG",
                            Summoner = "Rârgh",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 79,
                            Assists = 10,
                            Champion = "Sejuani",
                            Deaths = 10,
                            Kills = 0,
                            Opponent = "PTP2",
                            Role = "JNG",
                            Summoner = "Rârgh",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 80,
                            Assists = 11,
                            Champion = "Hecraim",
                            Deaths = 4,
                            Kills = 2,
                            Opponent = "TAS2",
                            Role = "JNG",
                            Summoner = "Rârgh",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 81,
                            Assists = 5,
                            Champion = "Jarvan-IV",
                            Deaths = 5,
                            Kills = 1,
                            Opponent = "YUP2",
                            Role = "JNG",
                            Summoner = "Rârgh",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 82,
                            Assists = 7,
                            Champion = "Yone",
                            Deaths = 5,
                            Kills = 5,
                            Opponent = "GURL",
                            Role = "MID",
                            Summoner = "Huebs",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 83,
                            Assists = 0,
                            Champion = "Yauso",
                            Deaths = 5,
                            Kills = 1,
                            Opponent = "INT2",
                            Role = "MID",
                            Summoner = "Huebs",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 84,
                            Assists = 8,
                            Champion = "Yone",
                            Deaths = 6,
                            Kills = 3,
                            Opponent = "PTP2",
                            Role = "MID",
                            Summoner = "Huebs",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 85,
                            Assists = 10,
                            Champion = "Azir",
                            Deaths = 4,
                            Kills = 4,
                            Opponent = "TAS2",
                            Role = "MID",
                            Summoner = "Huebs",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 86,
                            Assists = 5,
                            Champion = "Viktor",
                            Deaths = 2,
                            Kills = 1,
                            Opponent = "YUP2",
                            Role = "MID",
                            Summoner = "Huebs",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 87,
                            Assists = 10,
                            Champion = "Caitlyn",
                            Deaths = 1,
                            Kills = 7,
                            Opponent = "DD",
                            Role = "ADC",
                            Summoner = "Ssunrise",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 88,
                            Assists = 21,
                            Champion = "Lux",
                            Deaths = 2,
                            Kills = 2,
                            Opponent = "GURL",
                            Role = "ADC",
                            Summoner = "Ssunrise",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 89,
                            Assists = 2,
                            Champion = "Caitlyn",
                            Deaths = 3,
                            Kills = 1,
                            Opponent = "INT",
                            Role = "ADC",
                            Summoner = "Ssunrise",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 90,
                            Assists = 4,
                            Champion = "Kindred",
                            Deaths = 5,
                            Kills = 6,
                            Opponent = "PTP",
                            Role = "JNG",
                            Summoner = "Ssunrise",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 91,
                            Assists = 4,
                            Champion = "Kindred",
                            Deaths = 7,
                            Kills = 4,
                            Opponent = "TAS",
                            Role = "JNG",
                            Summoner = "Ssunrise",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 92,
                            Assists = 7,
                            Champion = "Kog'Maw",
                            Deaths = 4,
                            Kills = 5,
                            Opponent = "YUP",
                            Role = "ADC",
                            Summoner = "Ssunrise",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 93,
                            Assists = 10,
                            Champion = "Kai'sa",
                            Deaths = 1,
                            Kills = 14,
                            Opponent = "DD2",
                            Role = "ADC",
                            Summoner = "Ssunrise",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 94,
                            Assists = 5,
                            Champion = "Kai'sa",
                            Deaths = 1,
                            Kills = 14,
                            Opponent = "GURL2",
                            Role = "ADC",
                            Summoner = "Ssunrise",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 95,
                            Assists = 3,
                            Champion = "Kai'sa",
                            Deaths = 3,
                            Kills = 0,
                            Opponent = "INT2",
                            Role = "ADC",
                            Summoner = "Ssunrise",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 96,
                            Assists = 3,
                            Champion = "Miss-Fortune",
                            Deaths = 3,
                            Kills = 7,
                            Opponent = "PTP2",
                            Role = "ADC",
                            Summoner = "Ssunrise",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 97,
                            Assists = 12,
                            Champion = "Morgana",
                            Deaths = 0,
                            Kills = 0,
                            Opponent = "DD",
                            Role = "SUP",
                            Summoner = "Luciferalfa",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 98,
                            Assists = 12,
                            Champion = "Sona",
                            Deaths = 1,
                            Kills = 3,
                            Opponent = "GURL",
                            Role = "SUP",
                            Summoner = "Luciferalfa",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 99,
                            Assists = 3,
                            Champion = "Morgana",
                            Deaths = 6,
                            Kills = 0,
                            Opponent = "INT",
                            Role = "SUP",
                            Summoner = "Luciferalfa",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 100,
                            Assists = 6,
                            Champion = "Nautalis",
                            Deaths = 9,
                            Kills = 2,
                            Opponent = "PTP",
                            Role = "SUP",
                            Summoner = "Luciferalfa",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 101,
                            Assists = 7,
                            Champion = "Senna",
                            Deaths = 2,
                            Kills = 1,
                            Opponent = "TAS",
                            Role = "SUP",
                            Summoner = "Luciferalfa",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 102,
                            Assists = 11,
                            Champion = "Lulu",
                            Deaths = 3,
                            Kills = 0,
                            Opponent = "YUP",
                            Role = "SUP",
                            Summoner = "Luciferalfa",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 103,
                            Assists = 17,
                            Champion = "Galio",
                            Deaths = 2,
                            Kills = 2,
                            Opponent = "DD2",
                            Role = "SUP",
                            Summoner = "Luciferalfa",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 104,
                            Assists = 12,
                            Champion = "Galio",
                            Deaths = 1,
                            Kills = 1,
                            Opponent = "GURL2",
                            Role = "SUP",
                            Summoner = "Luciferalfa",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 105,
                            Assists = 2,
                            Champion = "Galio",
                            Deaths = 7,
                            Kills = 0,
                            Opponent = "INT2",
                            Role = "SUP",
                            Summoner = "Luciferalfa",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 106,
                            Assists = 3,
                            Champion = "Leona",
                            Deaths = 6,
                            Kills = 1,
                            Opponent = "PTP2",
                            Role = "SUP",
                            Summoner = "Luciferalfa",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 107,
                            Assists = 14,
                            Champion = "Braum",
                            Deaths = 9,
                            Kills = 1,
                            Opponent = "TAS2",
                            Role = "SUP",
                            Summoner = "Luciferalfa",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 108,
                            Assists = 5,
                            Champion = "Shen",
                            Deaths = 4,
                            Kills = 0,
                            Opponent = "YUP2",
                            Role = "SUP",
                            Summoner = "Luciferalfa",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 109,
                            Assists = 7,
                            Champion = "Gnar",
                            Deaths = 1,
                            Kills = 5,
                            Opponent = "DD",
                            Role = "TOP",
                            Summoner = "AllMightTheHero",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 110,
                            Assists = 9,
                            Champion = "Gnar",
                            Deaths = 4,
                            Kills = 8,
                            Opponent = "GURL",
                            Role = "TOP",
                            Summoner = "AllMightTheHero",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 111,
                            Assists = 8,
                            Champion = "Oriana",
                            Deaths = 1,
                            Kills = 2,
                            Opponent = "DD",
                            Role = "MID",
                            Summoner = "Chris-Sunga",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 112,
                            Assists = 3,
                            Champion = "Syndra",
                            Deaths = 3,
                            Kills = 2,
                            Opponent = "INT",
                            Role = "MID",
                            Summoner = "Chris-Sunga",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 113,
                            Assists = 7,
                            Champion = "Galio",
                            Deaths = 6,
                            Kills = 0,
                            Opponent = "PTP",
                            Role = "MID",
                            Summoner = "Chris-Sunga",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 114,
                            Assists = 3,
                            Champion = "Le-Blanc",
                            Deaths = 4,
                            Kills = 2,
                            Opponent = "TAS",
                            Role = "MID",
                            Summoner = "Chris-Sunga",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 115,
                            Assists = 9,
                            Champion = "Lee-sin",
                            Deaths = 4,
                            Kills = 4,
                            Opponent = "YUP",
                            Role = "JNG",
                            Summoner = "Chris-Sunga",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 116,
                            Assists = 12,
                            Champion = "Azir",
                            Deaths = 4,
                            Kills = 8,
                            Opponent = "DD2",
                            Role = "MID",
                            Summoner = "Chris-Sunga",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 117,
                            Assists = 7,
                            Champion = "Zilean",
                            Deaths = 2,
                            Kills = 3,
                            Opponent = "GURL2",
                            Role = "MID",
                            Summoner = "Chris-Sunga",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 118,
                            Assists = 8,
                            Champion = "Lucian",
                            Deaths = 3,
                            Kills = 8,
                            Opponent = "TAS2",
                            Role = "ADC",
                            Summoner = "Chris-Sunga",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 119,
                            Assists = 0,
                            Champion = "Kai'sa",
                            Deaths = 3,
                            Kills = 6,
                            Opponent = "TUP2",
                            Role = "ADC",
                            Summoner = "Chris-Sunga",
                            Team = "BBZ"
                        },
                        new
                        {
                            PlayerId = 120,
                            Assists = 4,
                            Champion = "Varus",
                            Deaths = 7,
                            Kills = 1,
                            Opponent = "PTP",
                            Role = "ADC",
                            Summoner = "Abhi Kris",
                            Team = "BBZ"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
