using Microsoft.EntityFrameworkCore;

namespace Stats.Models
{
  public class StatsContext : DbContext
  {
    public StatsContext(DbContextOptions<StatsContext> options)
      : base(options)
    {
    }

    public DbSet<Player> Players { get; set; }
    protected override void OnModelCreating(ModelBuilder builder)
     { 
      builder.Entity<Player>()
        .HasData(
          new Player { PlayerId = 1, Summoner = "Theroclease", Team = "GURL", Opponent = "TAS", Champion = "Caitlyn", Role = "ADC", Kills = 14, Deaths = 5, Assists = 7 },
          new Player { PlayerId = 2, Summoner = "Theroclease", Team = "GURL", Opponent = "YUP", Champion = "Jinx", Role = "ADC", Kills = 15, Deaths = 2, Assists = 8 },
          new Player { PlayerId = 3, Summoner = "Theroclease", Team = "GURL", Opponent = "DD", Champion = "Ezreal", Role = "ADC", Kills = 11, Deaths = 1, Assists = 12 },
          new Player { PlayerId = 4, Summoner = "Theroclease", Team = "GURL", Opponent = "INT", Champion = "Tristina", Role = "ADC", Kills = 7, Deaths = 4, Assists = 3 },
          new Player { PlayerId = 5, Summoner = "Theroclease", Team = "GURL", Opponent = "PTP", Champion = "Lucian", Role = "ADC", Kills = 3, Deaths = 7, Assists = 11 },
          new Player { PlayerId = 6, Summoner = "Theroclease", Team = "GURL", Opponent = "TAS2", Champion = "Thresh", Role = "SUP", Kills = 1, Deaths = 4, Assists = 15 },
          new Player { PlayerId = 7, Summoner = "Theroclease", Team = "GURL", Opponent = "YUP2", Champion = "Morgana", Role = "SUP", Kills = 3, Deaths = 7, Assists = 17 },
          new Player { PlayerId = 8, Summoner = "Theroclease", Team = "GURL", Opponent = "BBZ2", Champion = "Pyke", Role = "SUP", Kills = 1, Deaths = 6, Assists = 0 },
          new Player { PlayerId = 9, Summoner = "Theroclease", Team = "GURL", Opponent = "INT2", Champion = "Ashe", Role = "ADC", Kills = 2, Deaths = 7, Assists = 0 },
          new Player { PlayerId = 10, Summoner = "Theroclease", Team = "GURL", Opponent = "PTP2", Champion = "Caitlyn", Role = "ADC", Kills = 3, Deaths = 5, Assists = 2 },
          new Player { PlayerId = 11, Summoner = "BakinPancakes", Team = "GURL", Opponent = "YUP", Champion = "Urgot", Role = "TOP", Kills = 7, Deaths = 2, Assists = 11 },
          new Player { PlayerId = 12, Summoner = "BakinPancakes", Team = "GURL", Opponent = "BBZ", Champion = "Kled", Role = "TOP", Kills = 3, Deaths = 6, Assists = 3 },
          new Player { PlayerId = 13, Summoner = "BakinPancakes", Team = "GURL", Opponent = "DD", Champion = "Mordakaiser", Role = "TOP", Kills = 11, Deaths = 4, Assists = 10 },
          new Player { PlayerId = 14, Summoner = "BakinPancakes", Team = "GURL", Opponent = "INT", Champion = "Mordakaiser", Role = "TOP", Kills = 3, Deaths = 4, Assists = 1 },
          new Player { PlayerId = 15, Summoner = "BakinPancakes", Team = "GURL", Opponent = "PTP", Champion = "Kled", Role = "TOP", Kills = 6, Deaths = 6, Assists = 8 },
          new Player { PlayerId = 16, Summoner = "BakinPancakes", Team = "GURL", Opponent = "TAS2", Champion = "Mordakaiser", Role = "TOP", Kills = 7, Deaths = 7, Assists = 9 },
          new Player { PlayerId = 17, Summoner = "BakinPancakes", Team = "GURL", Opponent = "YUP2", Champion = "Urgot", Role = "TOP", Kills = 13, Deaths = 4, Assists = 8 },
          new Player { PlayerId = 18, Summoner = "BakinPancakes", Team = "GURL", Opponent = "BBZ2", Champion = "Urgot", Role = "TOP", Kills = 2, Deaths = 5, Assists = 3 },
          new Player { PlayerId = 19, Summoner = "BakinPancakes", Team = "GURL", Opponent = "DD2", Champion = "Urgot", Role = "TOP", Kills = 3, Deaths = 7, Assists = 4 },
          new Player { PlayerId = 20, Summoner = "BakinPancakes", Team = "GURL", Opponent = "INT2", Champion = "Poppy", Role = "TOP", Kills = 1, Deaths = 6, Assists = 2 },
          new Player { PlayerId = 21, Summoner = "BakinPancakes", Team = "GURL", Opponent = "PTP2", Champion = "Kled", Role = "TOP", Kills = 3, Deaths = 7, Assists = 5 },
          new Player { PlayerId = 22, Summoner = "Willow233", Team = "GURL", Opponent = "TAS", Champion = "Mordakaiser", Role = "TOP", Kills = 3, Deaths = 4, Assists = 3 },
          new Player { PlayerId = 23, Summoner = "Willow233", Team = "GURL", Opponent = "YUP", Champion = "Warwick", Role = "JNG", Kills = 1, Deaths = 10, Assists = 14 },
          new Player { PlayerId = 24, Summoner = "Willow233", Team = "GURL", Opponent = "BBZ", Champion = "Skarner", Role = "JNG", Kills = 2, Deaths = 3, Assists = 11 },
          new Player { PlayerId = 25, Summoner = "Willow233", Team = "GURL", Opponent = "DD", Champion = "Ammumu", Role = "JNG", Kills = 4, Deaths = 4, Assists = 20 },
          new Player { PlayerId = 26, Summoner = "Willow233", Team = "GURL", Opponent = "INT", Champion = "Skarner", Role = "JNG", Kills = 2, Deaths = 5, Assists = 4 },
          new Player { PlayerId = 27, Summoner = "Willow233", Team = "GURL", Opponent = "PTP", Champion = "Nocturne", Role = "JNG", Kills = 6, Deaths = 9, Assists = 5 },
          new Player { PlayerId = 28, Summoner = "Willow233", Team = "GURL", Opponent = "TAS2", Champion = "Hecraim", Role = "JNG", Kills = 4, Deaths = 9, Assists = 13 },
          new Player { PlayerId = 29, Summoner = "Willow233", Team = "GURL", Opponent = "YUP2", Champion = "Nunu", Role = "JNG", Kills = 3, Deaths = 8, Assists = 15 },
          new Player { PlayerId = 30, Summoner = "Willow233", Team = "GURL", Opponent = "BBZ2", Champion = "Nunu", Role = "JNG", Kills = 1, Deaths = 4, Assists = 3 },
          new Player { PlayerId = 31, Summoner = "Willow233", Team = "GURL", Opponent = "DD2", Champion = "Nocturne", Role = "JNG", Kills = 0, Deaths = 10, Assists = 7 },
          new Player { PlayerId = 32, Summoner = "XNek0X", Team = "GURL", Opponent = "TAS", Champion = "Malzahar", Role = "MID", Kills = 4, Deaths = 6, Assists = 12 },          
          new Player { PlayerId = 33, Summoner = "XNek0X", Team = "GURL", Opponent = "YUP", Champion = "Morgana", Role = "MID", Kills = 3, Deaths = 4, Assists = 17 },
          new Player { PlayerId = 34, Summoner = "XNek0X", Team = "GURL", Opponent = "BBZ", Champion = "Lissandra", Role = "MID", Kills = 10, Deaths = 5, Assists = 2 },
          new Player { PlayerId = 35, Summoner = "XNek0X", Team = "GURL", Opponent = "DD", Champion = "Brand", Role = "MID", Kills = 4, Deaths = 4, Assists = 11 },
          new Player { PlayerId = 36, Summoner = "XNek0X", Team = "GURL", Opponent = "INT", Champion = "Malzahar",  Role = "MID", Kills = 0, Deaths = 3, Assists = 4 },
          new Player { PlayerId = 37, Summoner = "XNek0X", Team = "GURL", Opponent = "PTP", Champion = "Brand", Role = "MID",  Kills = 3, Deaths = 5, Assists = 3 },
          new Player { PlayerId = 38, Summoner = "XNek0X", Team = "GURL", Opponent = "TAS2", Champion = "Lissandra", Role = "MID", Kills = 12, Deaths = 8, Assists = 7 },
          new Player { PlayerId = 39, Summoner = "XNek0X", Team = "GURL", Opponent = "YUP2", Champion = "Le-Blanc", Role = "MID", Kills = 3, Deaths = 4, Assists = 9 },
          new Player { PlayerId = 40, Summoner = "XNek0X", Team = "GURL", Opponent = "BBZ2", Champion = "Veigar", Role = "MID", Kills = 2, Deaths = 5, Assists = 3 },
          new Player { PlayerId = 41, Summoner = "XNek0X", Team = "GURL", Opponent = "DD2", Champion = "Malzahar", Role = "MID", Kills = 3, Deaths = 6, Assists = 4 }, 
          new Player { PlayerId = 42, Summoner = "XNek0X", Team = "GURL", Opponent = "INT2", Champion = "Annie", Role = "MID", Kills = 1, Deaths = 3, Assists = 0 },
          new Player { PlayerId = 43, Summoner = "XNek0X", Team = "GURL", Opponent = "PTP2", Champion = "Malzahar", Role = "MID", Kills = 3, Deaths = 4, Assists = 6 },
          new Player { PlayerId = 44, Summoner = "Mr-Turbo-Int", Team = "GURL", Opponent = "YUP", Champion = "Pyke", Role = "SUP", Kills = 1, Deaths = 6, Assists = 5 },
          new Player { PlayerId = 45, Summoner = "Mr-Turbo-Int", Team = "GURL", Opponent = "BBZ", Champion = "Jinx", Role = "ADC", Kills = 0, Deaths = 6, Assists = 7 },
          new Player { PlayerId = 46, Summoner = "Mr-Turbo-Int", Team = "GURL", Opponent = "DD", Champion = "Lux", Role = "SUP", Kills = 2, Deaths = 3, Assists = 10 },
          new Player { PlayerId = 47, Summoner = "Mr-Turbo-Int", Team = "GURL", Opponent = "INT", Champion = "Leona", Role = "SUP", Kills = 0, Deaths = 7, Assists = 8 },
          new Player { PlayerId = 48, Summoner = "Mr-Turbo-Int", Team = "GURL", Opponent = "PTP", Champion = "Leona", Role = "SUP", Kills = 0, Deaths = 9, Assists = 11 },
          new Player { PlayerId = 49, Summoner = "Mr-Turbo-Int", Team = "GURL", Opponent = "TAS2", Champion = "Ashe",  Role = "ADC", Kills = 4, Deaths = 8, Assists = 12 },
          new Player { PlayerId = 50, Summoner = "Mr-Turbo-Int", Team = "GURL", Opponent = "YUP2", Champion = "Ezreal", Role = "ADC", Kills = 6, Deaths = 6, Assists = 9 },
          new Player { PlayerId = 51, Summoner = "Mr-Turbo-Int", Team = "GURL", Opponent = "BBZ2", Champion = "Xayah", Role = "ADC", Kills = 1, Deaths = 5, Assists = 0 },
          new Player { PlayerId = 52, Summoner = "TyrantKingTyrone", Team = "GURL", Opponent = "TAS", Champion = "Graves", Role = "JNG", Kills = 3, Deaths = 3, Assists = 14 },
          new Player { PlayerId = 53, Summoner = "Vale-Claddath", Team = "GURL", Opponent = "TAS", Champion = "Thresh", Role = "SUP", Kills = 0, Deaths = 9, Assists = 14 },
          new Player { PlayerId = 54, Summoner = "Vale-Claddath", Team = "GURL", Opponent = "BBZ", Champion = "Senna", Role = "SUP", Kills = 3, Deaths = 5, Assists = 7 },
          new Player { PlayerId = 55, Summoner = "Truelax21", Team = "GURL", Opponent = "DD2", Champion = "Ashe", Role = "ADC", Kills = 4, Deaths = 5, Assists = 4 },
          new Player { PlayerId = 56, Summoner = "Truelax21", Team = "GURL", Opponent = "INT2", Champion = "Trundle", Role = "JNG", Kills = 3, Deaths = 7, Assists = 2 },
          new Player { PlayerId = 57, Summoner = "Truelax21", Team = "GURL", Opponent = "PTP2", Champion = "Hecraim", Role = "JNG", Kills = 3, Deaths = 7, Assists = 3 },
          new Player { PlayerId = 58, Summoner = "Warlock-Herald", Team = "GURL", Opponent = "DD2", Champion = "Nami", Role = "SUP", Kills = 0, Deaths = 3, Assists = 8 },
          new Player { PlayerId = 59, Summoner = "Unburdened", Team = "GURL", Opponent = "INT2", Champion = "Leona", Role = "SUP", Kills = 0, Deaths = 6, Assists = 1 },
          new Player { PlayerId = 60, Summoner = "Unburdened", Team = "GURL", Opponent = "PTP2", Champion = "Tahm Kench", Role = "SUP", Kills = 0, Deaths = 5, Assists = 5 },
          new Player { PlayerId = 61, Summoner = "ShieldedValor", Team = "BBZ", Opponent = "INT", Champion = "Maoki", Role = "TOP", Kills = 1, Deaths = 5, Assists = 2 }, 
          new Player { PlayerId = 62, Summoner = "ShieldedValor", Team = "BBZ", Opponent = "PTP", Champion = "Riven", Role = "TOP", Kills = 4, Deaths = 5, Assists = 6 },
          new Player { PlayerId = 63, Summoner = "ShieldedValor", Team = "BBZ", Opponent = "TAS", Champion = "Ornn", Role = "TOP", Kills = 1, Deaths = 4, Assists = 5 },
          new Player { PlayerId = 64, Summoner = "ShieldedValor", Team = "BBZ", Opponent = "YUP", Champion = "Jax", Role = "TOP", Kills = 10, Deaths = 3, Assists = 1 },
          new Player { PlayerId = 65, Summoner = "ShieldedValor", Team = "BBZ", Opponent = "DD2", Champion = "Shen", Role = "TOP", Kills = 4, Deaths = 1, Assists = 18 },
          new Player { PlayerId = 66, Summoner = "ShieldedValor", Team = "BBZ", Opponent = "GURL2", Champion = "Shen", Role = "TOP", Kills = 4, Deaths = 0, Assists = 9 },
          new Player { PlayerId = 67, Summoner = "ShieldedValor", Team = "BBZ", Opponent = "INT2", Champion = "Rumble", Role = "TOP", Kills = 2, Deaths = 1, Assists = 10 },
          new Player { PlayerId = 68, Summoner = "ShieldedValor", Team = "BBZ", Opponent = "PTP2", Champion = "Sylas", Role = "TOP", Kills = 3, Deaths = 4, Assists = 4 },
          new Player { PlayerId = 69, Summoner = "ShieldedValor", Team = "BBZ", Opponent = "TAS2", Champion = "Rumble", Role = "TOP", Kills = 4, Deaths = 2, Assists = 11 },                      
          new Player { PlayerId = 70, Summoner = "ShieldedValor", Team = "BBZ", Opponent = "YUP2", Champion = "Mordakaiser", Role = "TOP", Kills = 5, Deaths = 2, Assists = 6 },
          new Player { PlayerId = 71, Summoner = "Rârgh", Team = "BBZ", Opponent = "DD", Champion = "Hecraim", Role = "JNG", Kills = 1, Deaths = 2, Assists = 8 },
          new Player { PlayerId = 72, Summoner = "Rârgh", Team = "BBZ", Opponent = "GURL", Champion = "Sejuani", Role = "JNG", Kills = 7, Deaths = 6, Assists = 13 },
          new Player { PlayerId = 73, Summoner = "Rârgh", Team = "BBZ", Opponent = "INT", Champion = "Sejuani", Role = "JNG", Kills = 2, Deaths = 8, Assists = 3 },
          new Player { PlayerId = 74, Summoner = "Rârgh", Team = "BBZ", Opponent = "TAS", Champion = "Galio", Role = "SUP", Kills = 3, Deaths = 8, Assists = 3 },
          new Player { PlayerId = 75, Summoner = "Rârgh", Team = "BBZ", Opponent = "YUP", Champion = "Veigar", Role = "MID", Kills = 3, Deaths = 5, Assists = 6 },
          new Player { PlayerId = 76, Summoner = "Rârgh", Team = "BBZ", Opponent = "DD2", Champion = "Hecraim", Role = "JNG", Kills = 1, Deaths = 1, Assists = 19 },
          new Player { PlayerId = 77, Summoner = "Rârgh", Team = "BBZ", Opponent = "GURL2", Champion = "Hecraim", Role = "JNG", Kills = 3, Deaths = 3, Assists = 14 },
          new Player { PlayerId = 78, Summoner = "Rârgh", Team = "BBZ", Opponent = "INT2", Champion = "Zac", Role = "JNG", Kills = 0, Deaths = 5, Assists = 2 },
          new Player { PlayerId = 79, Summoner = "Rârgh", Team = "BBZ", Opponent = "PTP2", Champion = "Sejuani", Role = "JNG", Kills = 0, Deaths = 10, Assists = 10 },
          new Player { PlayerId = 80, Summoner = "Rârgh", Team = "BBZ", Opponent = "TAS2", Champion = "Hecraim", Role = "JNG", Kills = 2, Deaths = 4, Assists = 11 },
          new Player { PlayerId = 81, Summoner = "Rârgh", Team = "BBZ", Opponent = "YUP2", Champion = "Jarvan-IV", Role = "JNG", Kills = 1, Deaths = 5, Assists = 5 },
          new Player { PlayerId = 82, Summoner = "Huebs", Team = "BBZ", Opponent = "GURL", Champion = "Yone", Role = "MID", Kills = 5, Deaths = 5, Assists = 7 },
          new Player { PlayerId = 83, Summoner = "Huebs", Team = "BBZ", Opponent = "INT2", Champion = "Yauso", Role = "MID", Kills = 1, Deaths = 5, Assists = 0 },
          new Player { PlayerId = 84, Summoner = "Huebs", Team = "BBZ", Opponent = "PTP2", Champion = "Yone", Role = "MID", Kills = 3, Deaths = 6, Assists = 8 },
          new Player { PlayerId = 85, Summoner = "Huebs", Team = "BBZ", Opponent = "TAS2", Champion = "Azir", Role = "MID", Kills = 4, Deaths = 4, Assists = 10 },
          new Player { PlayerId = 86, Summoner = "Huebs", Team = "BBZ", Opponent = "YUP2", Champion = "Viktor", Role = "MID", Kills = 1, Deaths = 2, Assists = 5 },
          new Player { PlayerId = 87, Summoner = "Ssunrise", Team = "BBZ", Opponent = "DD", Champion = "Caitlyn", Role = "ADC", Kills = 7, Deaths = 1, Assists = 10 },
          new Player { PlayerId = 88, Summoner = "Ssunrise", Team = "BBZ", Opponent = "GURL", Champion = "Lux", Role = "ADC", Kills = 2, Deaths = 2, Assists = 21 },
          new Player { PlayerId = 89, Summoner = "Ssunrise", Team = "BBZ", Opponent = "INT", Champion = "Caitlyn", Role = "ADC", Kills = 1, Deaths = 3, Assists = 2 },
          new Player { PlayerId = 90, Summoner = "Ssunrise", Team = "BBZ", Opponent = "PTP", Champion = "Kindred", Role = "JNG", Kills = 6, Deaths = 5, Assists = 4 },
          new Player { PlayerId = 91, Summoner = "Ssunrise", Team = "BBZ", Opponent = "TAS", Champion = "Kindred", Role = "JNG", Kills = 4, Deaths = 7, Assists = 4 },
          new Player { PlayerId = 92, Summoner = "Ssunrise", Team = "BBZ", Opponent = "YUP", Champion = "Kog'Maw", Role = "ADC", Kills = 5, Deaths = 4, Assists = 7 },
          new Player { PlayerId = 93, Summoner = "Ssunrise", Team = "BBZ", Opponent = "DD2", Champion = "Kai'sa", Role = "ADC", Kills = 14, Deaths = 1, Assists = 10 },
          new Player { PlayerId = 94, Summoner = "Ssunrise", Team = "BBZ", Opponent = "GURL2", Champion = "Kai'sa", Role = "ADC", Kills = 14, Deaths = 1, Assists = 5 },
          new Player { PlayerId = 95, Summoner = "Ssunrise", Team = "BBZ", Opponent = "INT2", Champion = "Kai'sa", Role = "ADC", Kills = 0, Deaths = 3, Assists = 3 },
          new Player { PlayerId = 96, Summoner = "Ssunrise", Team = "BBZ", Opponent = "PTP2", Champion = "Miss-Fortune", Role = "ADC", Kills = 7, Deaths = 3, Assists = 3 },
          new Player { PlayerId = 97, Summoner = "Luciferalfa", Team = "BBZ", Opponent = "DD", Champion = "Morgana", Role = "SUP", Kills = 0, Deaths = 0, Assists = 12 },
          new Player { PlayerId = 98, Summoner = "Luciferalfa", Team = "BBZ", Opponent = "GURL", Champion = "Sona", Role = "SUP", Kills = 3, Deaths = 1, Assists = 12 },
          new Player { PlayerId = 99, Summoner = "Luciferalfa", Team = "BBZ", Opponent = "INT", Champion = "Morgana", Role = "SUP", Kills = 0, Deaths = 6, Assists = 3 },
          new Player { PlayerId = 100, Summoner = "Luciferalfa", Team = "BBZ", Opponent = "PTP", Champion = "Nautalis", Role = "SUP", Kills = 2, Deaths = 9, Assists = 6 },
          new Player { PlayerId = 101, Summoner = "Luciferalfa", Team = "BBZ", Opponent = "TAS", Champion = "Senna", Role = "SUP", Kills = 1, Deaths = 2, Assists = 7 },
          new Player { PlayerId = 102, Summoner = "Luciferalfa", Team = "BBZ", Opponent = "YUP", Champion = "Lulu", Role = "SUP", Kills = 0, Deaths = 3, Assists = 11 },
          new Player { PlayerId = 103, Summoner = "Luciferalfa", Team = "BBZ", Opponent = "DD2", Champion = "Galio", Role = "SUP", Kills = 2, Deaths = 2, Assists = 17 },
          new Player { PlayerId = 104, Summoner = "Luciferalfa", Team = "BBZ", Opponent = "GURL2", Champion = "Galio", Role = "SUP", Kills = 1, Deaths = 1, Assists = 12 },
          new Player { PlayerId = 105, Summoner = "Luciferalfa", Team = "BBZ", Opponent = "INT2", Champion = "Galio", Role = "SUP", Kills = 0, Deaths = 7, Assists = 2 },
          new Player { PlayerId = 106, Summoner = "Luciferalfa", Team = "BBZ", Opponent = "PTP2", Champion = "Leona", Role = "SUP", Kills = 1, Deaths = 6, Assists = 3 },
          new Player { PlayerId = 107, Summoner = "Luciferalfa", Team = "BBZ", Opponent = "TAS2", Champion = "Braum", Role = "SUP", Kills = 1, Deaths = 9, Assists = 14 },
          new Player { PlayerId = 108, Summoner = "Luciferalfa", Team = "BBZ", Opponent = "YUP2", Champion = "Shen", Role = "SUP", Kills = 0, Deaths = 4, Assists = 5 },
          new Player { PlayerId = 109, Summoner = "AllMightTheHero", Team = "BBZ", Opponent = "DD", Champion = "Gnar", Role = "TOP", Kills = 5, Deaths = 1, Assists = 7 },
          new Player { PlayerId = 110, Summoner = "AllMightTheHero", Team = "BBZ", Opponent = "GURL", Champion = "Gnar", Role = "TOP", Kills = 8, Deaths = 4, Assists = 9 },
          new Player { PlayerId = 111, Summoner = "Chris-Sunga", Team = "BBZ", Opponent = "DD", Champion = "Oriana", Role = "MID", Kills = 2, Deaths = 1, Assists = 8 },
          new Player { PlayerId = 112, Summoner = "Chris-Sunga", Team = "BBZ", Opponent = "INT", Champion = "Syndra", Role = "MID", Kills = 2, Deaths = 3, Assists = 3 },
          new Player { PlayerId = 113, Summoner = "Chris-Sunga", Team = "BBZ", Opponent = "PTP", Champion = "Galio", Role = "MID", Kills = 0, Deaths = 6, Assists = 7 },
          new Player { PlayerId = 114, Summoner = "Chris-Sunga", Team = "BBZ", Opponent = "TAS", Champion = "Le-Blanc", Role = "MID", Kills = 2, Deaths = 4, Assists = 3 },
          new Player { PlayerId = 115, Summoner = "Chris-Sunga", Team = "BBZ", Opponent = "YUP", Champion = "Lee-sin", Role = "JNG", Kills = 4, Deaths = 4, Assists = 9 },
          new Player { PlayerId = 116, Summoner = "Chris-Sunga", Team = "BBZ", Opponent = "DD2", Champion = "Azir", Role = "MID", Kills = 8, Deaths = 4, Assists = 12 },
          new Player { PlayerId = 117, Summoner = "Chris-Sunga", Team = "BBZ", Opponent = "GURL2", Champion = "Zilean", Role = "MID", Kills = 3, Deaths = 2, Assists = 7 },
          new Player { PlayerId = 118, Summoner = "Chris-Sunga", Team = "BBZ", Opponent = "TAS2", Champion = "Lucian", Role = "ADC", Kills = 8, Deaths = 3, Assists = 8 },
          new Player { PlayerId = 119, Summoner = "Chris-Sunga", Team = "BBZ", Opponent = "TUP2", Champion = "Kai'sa", Role = "ADC", Kills = 6, Deaths = 3, Assists = 0 },
          new Player { PlayerId = 120, Summoner = "Abhi Kris", Team = "BBZ", Opponent = "PTP", Champion = "Varus", Role = "ADC", Kills = 1, Deaths = 7, Assists = 4 }
          );
    }
  }
}