using Microsoft.EntityFrameworkCore;

namespace Stats.Models
{
  public class StatsContext : DbContext
  {
    public StatsContext(DbContextOptions<StatsContext> options)
      : base(options)
    {
    }

    public DbSet<Player> Players { get; set; }
    protected override void OnModelCreating(ModelBuilder builder)
     { 
      builder.Entity<Player>()
        .HasData(
          new Player { PlayerId = 1, Summoner = "Theroclease", Team = "GURL", Opponent = "TAS", Champion = "Caitlyn", Role = "ADC", Kills = 14, Deaths = 5, Assists = 7 },
          new Player { PlayerId = 2, Summoner = "Theroclease", Team = "GURL", Opponent = "YUP", Champion = "Jinx", Role = "ADC", Kills = 15, Deaths = 2, Assists = 8 },
          new Player { PlayerId = 3, Summoner = "Theroclease", Team = "GURL", Opponent = "DD", Champion = "Ezreal", Role = "ADC", Kills = 11, Deaths = 1, Assists = 12 },
          new Player { PlayerId = 4, Summoner = "Theroclease", Team = "GURL", Opponent = "INT", Champion = "Tristina", Role = "ADC", Kills = 7, Deaths = 4, Assists = 3 },
          new Player { PlayerId = 5, Summoner = "Theroclease", Team = "GURL", Opponent = "PTP", Champion = "Lucian", Role = "ADC", Kills = 3, Deaths = 7, Assists = 11 },
          new Player { PlayerId = 6, Summoner = "Theroclease", Team = "GURL", Opponent = "TAS2", Champion = "Thresh", Role = "SUP", Kills = 1, Deaths = 4, Assists = 15 },
          new Player { PlayerId = 7, Summoner = "Theroclease", Team = "GURL", Opponent = "YUP2", Champion = "Morgana", Role = "SUP", Kills = 3, Deaths = 7, Assists = 17 },
          new Player { PlayerId = 8, Summoner = "Theroclease", Team = "GURL", Opponent = "BBZ2", Champion = "Pyke", Role = "SUP", Kills = 1, Deaths = 6, Assists = 0 },
          new Player { PlayerId = 9, Summoner = "Theroclease", Team = "GURL", Opponent = "INT2", Champion = "Ashe", Role = "ADC", Kills = 2, Deaths = 7, Assists = 0 },
          new Player { PlayerId = 10, Summoner = "Theroclease", Team = "GURL", Opponent = "PTP2", Champion = "Caitlyn", Role = "ADC", Kills = 3, Deaths = 5, Assists = 2 },
          new Player { PlayerId = 11, Summoner = "BakinPancakes", Team = "GURL", Opponent = "YUP", Champion = "Urgot", Role = "TOP", Kills = 7, Deaths = 2, Assists = 11 },
          new Player { PlayerId = 12, Summoner = "BakinPancakes", Team = "GURL", Opponent = "BBZ", Champion = "Kled", Role = "TOP", Kills = 3, Deaths = 6, Assists = 3 },
          new Player { PlayerId = 13, Summoner = "BakinPancakes", Team = "GURL", Opponent = "DD", Champion = "Mordakaiser", Role = "TOP", Kills = 11, Deaths = 4, Assists = 10 },
          new Player { PlayerId = 14, Summoner = "BakinPancakes", Team = "GURL", Opponent = "INT", Champion = "Mordakaiser", Role = "TOP", Kills = 3, Deaths = 4, Assists = 1 },
          new Player { PlayerId = 15, Summoner = "BakinPancakes", Team = "GURL", Opponent = "PTP", Champion = "Kled", Role = "TOP", Kills = 6, Deaths = 6, Assists = 8 },
          new Player { PlayerId = 16, Summoner = "BakinPancakes", Team = "GURL", Opponent = "TAS2", Champion = "Mordakaiser", Role = "TOP", Kills = 7, Deaths = 7, Assists = 9 },
          new Player { PlayerId = 17, Summoner = "BakinPancakes", Team = "GURL", Opponent = "YUP2", Champion = "Urgot", Role = "TOP", Kills = 13, Deaths = 4, Assists = 8 },
          new Player { PlayerId = 18, Summoner = "BakinPancakes", Team = "GURL", Opponent = "BBZ2", Champion = "Urgot", Role = "TOP", Kills = 2, Deaths = 5, Assists = 3 },
          new Player { PlayerId = 19, Summoner = "BakinPancakes", Team = "GURL", Opponent = "DD2", Champion = "Urgot", Role = "TOP", Kills = 3, Deaths = 7, Assists = 4 },
          new Player { PlayerId = 20, Summoner = "BakinPancakes", Team = "GURL", Opponent = "INT2", Champion = "Poppy", Role = "TOP", Kills = 1, Deaths = 6, Assists = 2 },
          new Player { PlayerId = 21, Summoner = "BakinPancakes", Team = "GURL", Opponent = "PTP2", Champion = "Kled", Role = "TOP", Kills = 3, Deaths = 7, Assists = 5 },
          new Player { PlayerId = 22, Summoner = "Willow233", Team = "GURL", Opponent = "TAS", Champion = "Mordakaiser", Role = "TOP", Kills = 3, Deaths = 4, Assists = 3 },
          new Player { PlayerId = 23, Summoner = "Willow233", Team = "GURL", Opponent = "YUP", Champion = "Warwick", Role = "JNG", Kills = 1, Deaths = 10, Assists = 14 },
          new Player { PlayerId = 24, Summoner = "Willow233", Team = "GURL", Opponent = "BBZ", Champion = "Skarner", Role = "JNG", Kills = 2, Deaths = 3, Assists = 11 },
          new Player { PlayerId = 25, Summoner = "Willow233", Team = "GURL", Opponent = "DD", Champion = "Ammumu", Role = "JNG", Kills = 4, Deaths = 4, Assists = 20 },
          new Player { PlayerId = 26, Summoner = "Willow233", Team = "GURL", Opponent = "INT", Champion = "Skarner", Role = "JNG", Kills = 2, Deaths = 5, Assists = 4 },
          new Player { PlayerId = 27, Summoner = "Willow233", Team = "GURL", Opponent = "PTP", Champion = "Nocturne", Role = "JNG", Kills = 6, Deaths = 9, Assists = 5 },
          new Player { PlayerId = 28, Summoner = "Willow233", Team = "GURL", Opponent = "TAS2", Champion = "Hecraim", Role = "JNG", Kills = 4, Deaths = 9, Assists = 13 },
          new Player { PlayerId = 29, Summoner = "Willow233", Team = "GURL", Opponent = "YUP2", Champion = "Nunu", Role = "JNG", Kills = 3, Deaths = 8, Assists = 15 },
          new Player { PlayerId = 30, Summoner = "Willow233", Team = "GURL", Opponent = "BBZ2", Champion = "Nunu", Role = "JNG", Kills = 1, Deaths = 4, Assists = 3 },
          new Player { PlayerId = 31, Summoner = "Willow233", Team = "GURL", Opponent = "DD2", Champion = "Nocturne", Role = "JNG", Kills = 0, Deaths = 10, Assists = 7 },
          new Player { PlayerId = 32, Summoner = "XNek0X", Team = "GURL", Opponent = "TAS", Champion = "Malzahar", Role = "MID", Kills = 4, Deaths = 6, Assists = 12 },          
          new Player { PlayerId = 33, Summoner = "XNek0X", Team = "GURL", Opponent = "YUP", Champion = "Morgana", Role = "MID", Kills = 3, Deaths = 4, Assists = 17 },
          new Player { PlayerId = 34, Summoner = "XNek0X", Team = "GURL", Opponent = "BBZ", Champion = "Lissandra", Role = "MID", Kills = 10, Deaths = 5, Assists = 2 },
          new Player { PlayerId = 35, Summoner = "XNek0X", Team = "GURL", Opponent = "DD", Champion = "Brand", Role = "MID", Kills = 4, Deaths = 4, Assists = 11 },
          new Player { PlayerId = 36, Summoner = "XNek0X", Team = "GURL", Opponent = "INT", Champion = "Malzahar",  Role = "MID", Kills = 0, Deaths = 3, Assists = 4 },
          new Player { PlayerId = 37, Summoner = "XNek0X", Team = "GURL", Opponent = "PTP", Champion = "Brand", Role = "MID",  Kills = 3, Deaths = 5, Assists = 3 },
          new Player { PlayerId = 38, Summoner = "XNek0X", Team = "GURL", Opponent = "TAS2", Champion = "Lissandra", Role = "MID", Kills = 12, Deaths = 8, Assists = 7 },
          new Player { PlayerId = 39, Summoner = "XNek0X", Team = "GURL", Opponent = "YUP2", Champion = "Le-Blanc", Role = "MID", Kills = 3, Deaths = 4, Assists = 9 },
          new Player { PlayerId = 40, Summoner = "XNek0X", Team = "GURL", Opponent = "BBZ2", Champion = "Veigar", Role = "MID", Kills = 2, Deaths = 5, Assists = 3 },
          new Player { PlayerId = 41, Summoner = "XNek0X", Team = "GURL", Opponent = "DD2", Champion = "Malzahar", Role = "MID", Kills = 3, Deaths = 6, Assists = 4 }, 
          new Player { PlayerId = 42, Summoner = "XNek0X", Team = "GURL", Opponent = "INT2", Champion = "Annie", Role = "MID", Kills = 1, Deaths = 3, Assists = 0 },
          new Player { PlayerId = 43, Summoner = "XNek0X", Team = "GURL", Opponent = "PTP2", Champion = "Malzahar", Role = "MID", Kills = 3, Deaths = 4, Assists = 6 },
          new Player { PlayerId = 44, Summoner = "Mr-Turbo-Int", Team = "GURL", Opponent = "YUP", Champion = "Pyke", Role = "SUP", Kills = 1, Deaths = 6, Assists = 5 },
          new Player { PlayerId = 45, Summoner = "Mr-Turbo-Int", Team = "GURL", Opponent = "BBZ", Champion = "Jinx", Role = "ADC", Kills = 0, Deaths = 6, Assists = 7 },
          new Player { PlayerId = 46, Summoner = "Mr-Turbo-Int", Team = "GURL", Opponent = "DD", Champion = "Lux", Role = "SUP", Kills = 2, Deaths = 3, Assists = 10 },
          new Player { PlayerId = 47, Summoner = "Mr-Turbo-Int", Team = "GURL", Opponent = "INT", Champion = "Leona", Role = "SUP", Kills = 0, Deaths = 7, Assists = 8 },
          new Player { PlayerId = 48, Summoner = "Mr-Turbo-Int", Team = "GURL", Opponent = "PTP", Champion = "Leona", Role = "SUP", Kills = 0, Deaths = 9, Assists = 11 },
          new Player { PlayerId = 49, Summoner = "Mr-Turbo-Int", Team = "GURL", Opponent = "TAS2", Champion = "Ashe",  Role = "ADC", Kills = 4, Deaths = 8, Assists = 12 },
          new Player { PlayerId = 50, Summoner = "Mr-Turbo-Int", Team = "GURL", Opponent = "YUP2", Champion = "Ezreal", Role = "ADC", Kills = 6, Deaths = 6, Assists = 9 },
          new Player { PlayerId = 51, Summoner = "Mr-Turbo-Int", Team = "GURL", Opponent = "BBZ2", Champion = "Xayah", Role = "ADC", Kills = 1, Deaths = 5, Assists = 0 },
          new Player { PlayerId = 52, Summoner = "TyrantKingTyrone", Team = "GURL", Opponent = "TAS", Champion = "Graves", Role = "JNG", Kills = 3, Deaths = 3, Assists = 14 },
          new Player { PlayerId = 53, Summoner = "Vale-Claddath", Team = "GURL", Opponent = "TAS", Champion = "Thresh", Role = "SUP", Kills = 0, Deaths = 9, Assists = 14 },
          new Player { PlayerId = 54, Summoner = "Vale-Claddath", Team = "GURL", Opponent = "BBZ", Champion = "Senna", Role = "SUP", Kills = 3, Deaths = 5, Assists = 7 },
          new Player { PlayerId = 55, Summoner = "Truelax21", Team = "GURL", Opponent = "DD2", Champion = "Ashe", Role = "ADC", Kills = 4, Deaths = 5, Assists = 4 },
          new Player { PlayerId = 56, Summoner = "Truelax21", Team = "GURL", Opponent = "INT2", Champion = "Trundle", Role = "JNG", Kills = 3, Deaths = 7, Assists = 2 },
          new Player { PlayerId = 57, Summoner = "Truelax21", Team = "GURL", Opponent = "PTP2", Champion = "Hecraim", Role = "JNG", Kills = 3, Deaths = 7, Assists = 3 },
          new Player { PlayerId = 58, Summoner = "Warlock-Herald", Team = "GURL", Opponent = "DD2", Champion = "Nami", Role = "SUP", Kills = 0, Deaths = 3, Assists = 8 },
          new Player { PlayerId = 59, Summoner = "Unburdened", Team = "GURL", Opponent = "INT2", Champion = "Leona", Role = "SUP", Kills = 0, Deaths = 6, Assists = 1 },
          new Player { PlayerId = 60, Summoner = "Unburdened", Team = "GURL", Opponent = "PTP2", Champion = "Tahm Kench", Role = "SUP", Kills = 0, Deaths = 5, Assists = 5 },
          new Player { PlayerId = 61, Summoner = "ShieldedValor", Team = "BBZ", Opponent = "INT", Champion = "Maoki", Role = "TOP", Kills = 1, Deaths = 5, Assists = 2 }, 
          new Player { PlayerId = 62, Summoner = "ShieldedValor", Team = "BBZ", Opponent = "PTP", Champion = "Riven", Role = "TOP", Kills = 4, Deaths = 5, Assists = 6 },
          new Player { PlayerId = 63, Summoner = "ShieldedValor", Team = "BBZ", Opponent = "TAS", Champion = "Ornn", Role = "TOP", Kills = 1, Deaths = 4, Assists = 5 },
          new Player { PlayerId = 64, Summoner = "ShieldedValor", Team = "BBZ", Opponent = "YUP", Champion = "Jax", Role = "TOP", Kills = 10, Deaths = 3, Assists = 1 },
          new Player { PlayerId = 65, Summoner = "ShieldedValor", Team = "BBZ", Opponent = "DD2", Champion = "Shen", Role = "TOP", Kills = 4, Deaths = 1, Assists = 18 },
          new Player { PlayerId = 66, Summoner = "ShieldedValor", Team = "BBZ", Opponent = "GURL2", Champion = "Shen", Role = "TOP", Kills = 4, Deaths = 0, Assists = 9 },
          new Player { PlayerId = 67, Summoner = "ShieldedValor", Team = "BBZ", Opponent = "INT2", Champion = "Rumble", Role = "TOP", Kills = 2, Deaths = 1, Assists = 10 },
          new Player { PlayerId = 68, Summoner = "ShieldedValor", Team = "BBZ", Opponent = "PTP2", Champion = "Sylas", Role = "TOP", Kills = 3, Deaths = 4, Assists = 4 },
          new Player { PlayerId = 69, Summoner = "ShieldedValor", Team = "BBZ", Opponent = "TAS2", Champion = "Rumble", Role = "TOP", Kills = 4, Deaths = 2, Assists = 11 },                      
          new Player { PlayerId = 70, Summoner = "ShieldedValor", Team = "BBZ", Opponent = "YUP2", Champion = "Mordakaiser", Role = "TOP", Kills = 5, Deaths = 2, Assists = 6 },
          new Player { PlayerId = 71, Summoner = "Rârgh", Team = "BBZ", Opponent = "DD", Champion = "Hecraim", Role = "JNG", Kills = 1, Deaths = 2, Assists = 8 },
          new Player { PlayerId = 72, Summoner = "Rârgh", Team = "BBZ", Opponent = "GURL", Champion = "Sejuani", Role = "JNG", Kills = 7, Deaths = 6, Assists = 13 },
          new Player { PlayerId = 73, Summoner = "Rârgh", Team = "BBZ", Opponent = "INT", Champion = "Sejuani", Role = "JNG", Kills = 2, Deaths = 8, Assists = 3 },
          new Player { PlayerId = 74, Summoner = "Rârgh", Team = "BBZ", Opponent = "TAS", Champion = "Galio", Role = "SUP", Kills = 3, Deaths = 8, Assists = 3 },
          new Player { PlayerId = 75, Summoner = "Rârgh", Team = "BBZ", Opponent = "YUP", Champion = "Veigar", Role = "MID", Kills = 3, Deaths = 5, Assists = 6 },
          new Player { PlayerId = 76, Summoner = "Rârgh", Team = "BBZ", Opponent = "DD2", Champion = "Hecraim", Role = "JNG", Kills = 1, Deaths = 1, Assists = 19 },
          new Player { PlayerId = 77, Summoner = "Rârgh", Team = "BBZ", Opponent = "GURL2", Champion = "Hecraim", Role = "JNG", Kills = 3, Deaths = 3, Assists = 14 },
          new Player { PlayerId = 78, Summoner = "Rârgh", Team = "BBZ", Opponent = "INT2", Champion = "Zac", Role = "JNG", Kills = 0, Deaths = 5, Assists = 2 },
          new Player { PlayerId = 79, Summoner = "Rârgh", Team = "BBZ", Opponent = "PTP2", Champion = "Sejuani", Role = "JNG", Kills = 0, Deaths = 10, Assists = 10 },
          new Player { PlayerId = 80, Summoner = "Rârgh", Team = "BBZ", Opponent = "TAS2", Champion = "Hecraim", Role = "JNG", Kills = 2, Deaths = 4, Assists = 11 },
          new Player { PlayerId = 81, Summoner = "Rârgh", Team = "BBZ", Opponent = "YUP2", Champion = "Jarvan-IV", Role = "JNG", Kills = 1, Deaths = 5, Assists = 5 },
          new Player { PlayerId = 82, Summoner = "Huebs", Team = "BBZ", Opponent = "GURL", Champion = "Yone", Role = "MID", Kills = 5, Deaths = 5, Assists = 7 },
          new Player { PlayerId = 83, Summoner = "Huebs", Team = "BBZ", Opponent = "INT2", Champion = "Yauso", Role = "MID", Kills = 1, Deaths = 5, Assists = 0 },
          new Player { PlayerId = 84, Summoner = "Huebs", Team = "BBZ", Opponent = "PTP2", Champion = "Yone", Role = "MID", Kills = 3, Deaths = 6, Assists = 8 },
          new Player { PlayerId = 85, Summoner = "Huebs", Team = "BBZ", Opponent = "TAS2", Champion = "Azir", Role = "MID", Kills = 4, Deaths = 4, Assists = 10 },
          new Player { PlayerId = 86, Summoner = "Huebs", Team = "BBZ", Opponent = "YUP2", Champion = "Viktor", Role = "MID", Kills = 1, Deaths = 2, Assists = 5 },
          new Player { PlayerId = 87, Summoner = "Ssunrise", Team = "BBZ", Opponent = "DD", Champion = "Caitlyn", Role = "ADC", Kills = 7, Deaths = 1, Assists = 10 },
          new Player { PlayerId = 88, Summoner = "Ssunrise", Team = "BBZ", Opponent = "GURL", Champion = "Lux", Role = "ADC", Kills = 2, Deaths = 2, Assists = 21 },
          new Player { PlayerId = 89, Summoner = "Ssunrise", Team = "BBZ", Opponent = "INT", Champion = "Caitlyn", Role = "ADC", Kills = 1, Deaths = 3, Assists = 2 },
          new Player { PlayerId = 90, Summoner = "Ssunrise", Team = "BBZ", Opponent = "PTP", Champion = "Kindred", Role = "JNG", Kills = 6, Deaths = 5, Assists = 4 },
          new Player { PlayerId = 91, Summoner = "Ssunrise", Team = "BBZ", Opponent = "TAS", Champion = "Kindred", Role = "JNG", Kills = 4, Deaths = 7, Assists = 4 },
          new Player { PlayerId = 92, Summoner = "Ssunrise", Team = "BBZ", Opponent = "YUP", Champion = "Kog'Maw", Role = "ADC", Kills = 5, Deaths = 4, Assists = 7 },
          new Player { PlayerId = 93, Summoner = "Ssunrise", Team = "BBZ", Opponent = "DD2", Champion = "Kai'sa", Role = "ADC", Kills = 14, Deaths = 1, Assists = 10 },
          new Player { PlayerId = 94, Summoner = "Ssunrise", Team = "BBZ", Opponent = "GURL2", Champion = "Kai'sa", Role = "ADC", Kills = 14, Deaths = 1, Assists = 5 },
          new Player { PlayerId = 95, Summoner = "Ssunrise", Team = "BBZ", Opponent = "INT2", Champion = "Kai'sa", Role = "ADC", Kills = 0, Deaths = 3, Assists = 3 },
          new Player { PlayerId = 96, Summoner = "Ssunrise", Team = "BBZ", Opponent = "PTP2", Champion = "Miss-fortune", Role = "ADC", Kills = 7, Deaths = 3, Assists = 3 },
          new Player { PlayerId = 97, Summoner = "Luciferalfa", Team = "BBZ", Opponent = "DD", Champion = "Morgana", Role = "SUP", Kills = 0, Deaths = 0, Assists = 12 },
          new Player { PlayerId = 98, Summoner = "Luciferalfa", Team = "BBZ", Opponent = "GURL", Champion = "Sona", Role = "SUP", Kills = 3, Deaths = 1, Assists = 12 },
          new Player { PlayerId = 99, Summoner = "Luciferalfa", Team = "BBZ", Opponent = "INT", Champion = "Morgana", Role = "SUP", Kills = 0, Deaths = 6, Assists = 3 },
          new Player { PlayerId = 100, Summoner = "Luciferalfa", Team = "BBZ", Opponent = "PTP", Champion = "Nautalis", Role = "SUP", Kills = 2, Deaths = 9, Assists = 6 },
          new Player { PlayerId = 101, Summoner = "Luciferalfa", Team = "BBZ", Opponent = "TAS", Champion = "Senna", Role = "SUP", Kills = 1, Deaths = 2, Assists = 7 },
          new Player { PlayerId = 102, Summoner = "Luciferalfa", Team = "BBZ", Opponent = "YUP", Champion = "Lulu", Role = "SUP", Kills = 0, Deaths = 3, Assists = 11 },
          new Player { PlayerId = 103, Summoner = "Luciferalfa", Team = "BBZ", Opponent = "DD2", Champion = "Galio", Role = "SUP", Kills = 2, Deaths = 2, Assists = 17 },
          new Player { PlayerId = 104, Summoner = "Luciferalfa", Team = "BBZ", Opponent = "GURL2", Champion = "Galio", Role = "SUP", Kills = 1, Deaths = 1, Assists = 12 },
          new Player { PlayerId = 105, Summoner = "Luciferalfa", Team = "BBZ", Opponent = "INT2", Champion = "Galio", Role = "SUP", Kills = 0, Deaths = 7, Assists = 2 },
          new Player { PlayerId = 106, Summoner = "Luciferalfa", Team = "BBZ", Opponent = "PTP2", Champion = "Leona", Role = "SUP", Kills = 1, Deaths = 6, Assists = 3 },
          new Player { PlayerId = 107, Summoner = "Luciferalfa", Team = "BBZ", Opponent = "TAS2", Champion = "Braum", Role = "SUP", Kills = 1, Deaths = 9, Assists = 14 },
          new Player { PlayerId = 108, Summoner = "Luciferalfa", Team = "BBZ", Opponent = "YUP2", Champion = "Shen", Role = "SUP", Kills = 0, Deaths = 4, Assists = 5 },
          new Player { PlayerId = 109, Summoner = "AllMightTheHero", Team = "BBZ", Opponent = "DD", Champion = "Gnar", Role = "TOP", Kills = 5, Deaths = 1, Assists = 7 },
          new Player { PlayerId = 110, Summoner = "AllMightTheHero", Team = "BBZ", Opponent = "GURL", Champion = "Gnar", Role = "TOP", Kills = 8, Deaths = 4, Assists = 9 },
          new Player { PlayerId = 111, Summoner = "Chris-Sunga", Team = "BBZ", Opponent = "DD", Champion = "Oriana", Role = "MID", Kills = 2, Deaths = 1, Assists = 8 },
          new Player { PlayerId = 112, Summoner = "Chris-Sunga", Team = "BBZ", Opponent = "INT", Champion = "Syndra", Role = "MID", Kills = 2, Deaths = 3, Assists = 3 },
          new Player { PlayerId = 113, Summoner = "Chris-Sunga", Team = "BBZ", Opponent = "PTP", Champion = "Galio", Role = "MID", Kills = 0, Deaths = 6, Assists = 7 },
          new Player { PlayerId = 114, Summoner = "Chris-Sunga", Team = "BBZ", Opponent = "TAS", Champion = "Le-Blanc", Role = "MID", Kills = 2, Deaths = 4, Assists = 3 },
          new Player { PlayerId = 115, Summoner = "Chris-Sunga", Team = "BBZ", Opponent = "YUP", Champion = "Lee-sin", Role = "JNG", Kills = 4, Deaths = 4, Assists = 9 },
          new Player { PlayerId = 116, Summoner = "Chris-Sunga", Team = "BBZ", Opponent = "DD2", Champion = "Azir", Role = "MID", Kills = 8, Deaths = 4, Assists = 12 },
          new Player { PlayerId = 117, Summoner = "Chris-Sunga", Team = "BBZ", Opponent = "GURL2", Champion = "Zilean", Role = "MID", Kills = 3, Deaths = 2, Assists = 7 },
          new Player { PlayerId = 118, Summoner = "Chris-Sunga", Team = "BBZ", Opponent = "TAS2", Champion = "Lucian", Role = "ADC", Kills = 8, Deaths = 3, Assists = 8 },
          new Player { PlayerId = 119, Summoner = "Chris-Sunga", Team = "BBZ", Opponent = "TUP2", Champion = "Kai'sa", Role = "ADC", Kills = 6, Deaths = 3, Assists = 0 },
          new Player { PlayerId = 120, Summoner = "Abhi Kris", Team = "BBZ", Opponent = "PTP", Champion = "Varus", Role = "ADC", Kills = 1, Deaths = 7, Assists = 4 },
          new Player { PlayerId = 121, Summoner = "Brocklee900", Team = "INT", Opponent = "PTP", Champion = "Camile", Role = "TOP", Kills = 5, Deaths = 2, Assists = 10 },
          new Player { PlayerId = 122, Summoner = "Brocklee900", Team = "INT", Opponent = "TAS", Champion = "Camile", Role = "TOP", Kills = 9, Deaths = 1, Assists = 7 },
          new Player { PlayerId = 123, Summoner = "Brocklee900", Team = "INT", Opponent = "YUP", Champion = "Shen", Role = "TOP", Kills = 1, Deaths = 0, Assists = 9 },
          new Player { PlayerId = 124, Summoner = "Brocklee900", Team = "INT", Opponent = "BBZ", Champion = "Shen", Role = "TOP", Kills = 3, Deaths = 1, Assists = 15 },
          new Player { PlayerId = 125, Summoner = "Brocklee900", Team = "INT", Opponent = "DD", Champion = "Camile", Role = "MID", Kills = 8, Deaths = 6, Assists = 14 },
          new Player { PlayerId = 126, Summoner = "Brocklee900", Team = "INT", Opponent = "GURL", Champion = "Ekko", Role = "MID", Kills = 3, Deaths = 1, Assists = 6 },
          new Player { PlayerId = 127, Summoner = "Brocklee900", Team = "INT", Opponent = "PTP2", Champion = "Shen", Role = "TOP", Kills = 2, Deaths = 4, Assists = 2 },
          new Player { PlayerId = 128, Summoner = "Brocklee900", Team = "INT", Opponent = "TAS2", Champion = "Camile", Role = "TOP", Kills = 6, Deaths = 4, Assists = 10 },
          new Player { PlayerId = 129, Summoner = "Brocklee900", Team = "INT", Opponent = "YUP2", Champion = "Mordakaiser", Role = "TOP", Kills = 8, Deaths = 1, Assists = 1 },
          new Player { PlayerId = 130, Summoner = "Brocklee900", Team = "INT", Opponent = "BBZ2", Champion = "Shen", Role = "TOP", Kills = 1, Deaths = 0, Assists = 10 },
          new Player { PlayerId = 131, Summoner = "Brocklee900", Team = "INT", Opponent = "DD2", Champion = "Camile", Role = "TOP", Kills = 5, Deaths = 4, Assists = 7 },
          new Player { PlayerId = 132, Summoner = "Brocklee900", Team = "INT", Opponent = "GURL2", Champion = "Vi", Role = "JNG", Kills = 11, Deaths = 2, Assists = 9 },
          new Player { PlayerId = 133, Summoner = "BoExplode87", Team = "INT", Opponent = "PTP", Champion = "Volibear", Role = "JNG", Kills = 6, Deaths = 1, Assists = 14 },
          new Player { PlayerId = 134, Summoner = "BoExplode87", Team = "INT", Opponent = "TAS", Champion = "Volibear", Role = "JNG", Kills = 5, Deaths = 1, Assists = 22 },
          new Player { PlayerId = 135, Summoner = "BoExplode87", Team = "INT", Opponent = "YUP", Champion = "Trundle", Role = "JNG", Kills = 3, Deaths = 0, Assists = 13 },
          new Player { PlayerId = 136, Summoner = "BoExplode87", Team = "INT", Opponent = "BBZ", Champion = "Olaf", Role = "JNG", Kills = 10, Deaths = 2, Assists = 13 },
          new Player { PlayerId = 137, Summoner = "BoExplode87", Team = "INT", Opponent = "DD", Champion = "Lee-sin", Role = "JNG", Kills = 2, Deaths = 11, Assists = 18 },
          new Player { PlayerId = 138, Summoner = "BoExplode87", Team = "INT", Opponent = "GURL", Champion = "Olaf", Role = "JNG", Kills = 6, Deaths = 5, Assists = 9 },
          new Player { PlayerId = 139, Summoner = "BoExplode87", Team = "INT", Opponent = "PTP2", Champion = "Ekko", Role = "JNG", Kills = 0, Deaths = 8, Assists = 4 },
          new Player { PlayerId = 140, Summoner = "BoExplode87", Team = "INT", Opponent = "TAS2", Champion = "Sejuani", Role = "JNG", Kills = 8, Deaths = 4, Assists = 15 },
          new Player { PlayerId = 141, Summoner = "BoExplode87", Team = "INT", Opponent = "YUP2", Champion = "Sejuani", Role = "JNG", Kills = 3, Deaths = 2, Assists = 14 },
          new Player { PlayerId = 142, Summoner = "BoExplode87", Team = "INT", Opponent = "BBZ2", Champion = "Sejuani", Role = "JNG", Kills = 3, Deaths = 2, Assists = 14 },
          new Player { PlayerId = 143, Summoner = "BoExplode87", Team = "INT", Opponent = "DD2", Champion = "Sejuani", Role = "JNG", Kills = 3, Deaths = 5, Assists = 15 },
          new Player { PlayerId = 144, Summoner = "BoExplode87", Team = "INT", Opponent = "GURL2", Champion = "Katarina", Role = "MID", Kills = 7, Deaths = 2, Assists = 14 },
          new Player { PlayerId = 145, Summoner = "Evolvednewb", Team = "INT", Opponent = "PTP", Champion = "Oriana", Role = "MID", Kills = 3, Deaths = 1, Assists = 11 },
          new Player { PlayerId = 146, Summoner = "Evolvednewb", Team = "INT", Opponent = "TAS", Champion = "Viktor", Role = "MID", Kills = 5, Deaths = 3, Assists = 14 },
          new Player { PlayerId = 147, Summoner = "Evolvednewb", Team = "INT", Opponent = "YUP", Champion = "Ziggs", Role = "MID", Kills = 2, Deaths = 0, Assists = 10 },
          new Player { PlayerId = 148, Summoner = "Evolvednewb", Team = "INT", Opponent = "BBZ", Champion = "Azir", Role = "MID", Kills = 5, Deaths = 0, Assists = 10 },
          new Player { PlayerId = 149, Summoner = "Evolvednewb", Team = "INT", Opponent = "PTP2", Champion = "Ziggs", Role = "MID", Kills = 2, Deaths = 6, Assists = 5 },
          new Player { PlayerId = 150, Summoner = "Evolvednewb", Team = "INT", Opponent = "TAS2", Champion = "Syndra", Role = "MID", Kills = 3, Deaths = 3, Assists = 10 },
          new Player { PlayerId = 151, Summoner = "Evolvednewb", Team = "INT", Opponent = "YUP2", Champion = "Viktor", Role = "MID", Kills = 2, Deaths = 0, Assists = 13 },
          new Player { PlayerId = 152, Summoner = "Evolvednewb", Team = "INT", Opponent = "BBZ2", Champion = "Syndra", Role = "MID", Kills = 6, Deaths = 0, Assists = 11 },
          new Player { PlayerId = 153, Summoner = "Evolvednewb", Team = "INT", Opponent = "DD2", Champion = "Viktor", Role = "MID", Kills = 6, Deaths = 1, Assists = 7 },
          new Player { PlayerId = 154, Summoner = "Evolvednewb", Team = "INT", Opponent = "GURL2", Champion = "Cassiopia", Role = "TOP", Kills = 6, Deaths = 2, Assists = 5 },
          new Player { PlayerId = 155, Summoner = "KennyHammerspike", Team = "INT", Opponent = "PTP", Champion = "Caitlyn", Role = "ADC", Kills = 9, Deaths = 1, Assists = 10 },
          new Player { PlayerId = 156, Summoner = "KennyHammerspike", Team = "INT", Opponent = "TAS", Champion = "Ezreal", Role = "ADC", Kills = 10, Deaths = 3, Assists = 13 },
          new Player { PlayerId = 157, Summoner = "KennyHammerspike", Team = "INT", Opponent = "YUP", Champion = "Caitlyn", Role = "ADC", Kills = 8, Deaths = 1, Assists = 4 },
          new Player { PlayerId = 158, Summoner = "KennyHammerspike", Team = "INT", Opponent = "BBZ", Champion = "Ezreal", Role = "ADC", Kills = 5, Deaths = 1, Assists = 10 },
          new Player { PlayerId = 159, Summoner = "KennyHammerspike", Team = "INT", Opponent = "DD", Champion = "Heimerdinger", Role = "ADC", Kills = 13, Deaths = 6, Assists = 8 },
          new Player { PlayerId = 160, Summoner = "KennyHammerspike", Team = "INT", Opponent = "GURL", Champion = "Ezreal", Role = "ADC", Kills = 11, Deaths = 2, Assists = 4 },
          new Player { PlayerId = 161, Summoner = "KennyHammerspike", Team = "INT", Opponent = "PTP2", Champion = "Ezreal", Role = "ADC", Kills = 2, Deaths = 5, Assists = 4 },
          new Player { PlayerId = 162, Summoner = "KennyHammerspike", Team = "INT", Opponent = "TAS2", Champion = "Caitlyn", Role = "ADC", Kills = 5, Deaths = 4, Assists = 12 },
          new Player { PlayerId = 163, Summoner = "KennyHammerspike", Team = "INT", Opponent = "YUP2", Champion = "Miss-fortune", Role = "ADC", Kills = 5, Deaths = 1, Assists = 10 },
          new Player { PlayerId = 164, Summoner = "KennyHammerspike", Team = "INT", Opponent = "BBZ2", Champion = "Vayne", Role = "ADC", Kills = 11, Deaths = 1, Assists = 7 },
          new Player { PlayerId = 165, Summoner = "KennyHammerspike", Team = "INT", Opponent = "DD2", Champion = "Vayne", Role = "ADC", Kills = 6, Deaths = 1, Assists = 9 },
          new Player { PlayerId = 166, Summoner = "KennyHammerspike", Team = "INT", Opponent = "GURL2", Champion = "Jhin", Role = "ADC", Kills = 5, Deaths = 1, Assists = 3 },
          new Player { PlayerId = 167, Summoner = "HeWhoSlopps", Team = "INT", Opponent = "PTP", Champion = "Nautalis", Role = "SUP", Kills = 2, Deaths = 3, Assists = 15 },
          new Player { PlayerId = 168, Summoner = "HeWhoSlopps", Team = "INT", Opponent = "TAS", Champion = "Nautalis", Role = "SUP", Kills = 2, Deaths = 3, Assists = 19 },
          new Player { PlayerId = 169, Summoner = "HeWhoSlopps", Team = "INT", Opponent = "YUP", Champion = "Nautalis", Role = "SUP", Kills = 3, Deaths = 0, Assists = 9 },
          new Player { PlayerId = 170, Summoner = "HeWhoSlopps", Team = "INT", Opponent = "BBZ", Champion = "Braum", Role = "SUP", Kills = 2, Deaths = 2, Assists = 8 },
          new Player { PlayerId = 171, Summoner = "HeWhoSlopps", Team = "INT", Opponent = "DD", Champion = "Fiddlesticks", Role = "SUP", Kills = 2, Deaths = 9, Assists = 21 },
          new Player { PlayerId = 172, Summoner = "HeWhoSlopps", Team = "INT", Opponent = "GURL", Champion = "Nautalis", Role = "SUP", Kills = 0, Deaths = 3, Assists = 12 },
          new Player { PlayerId = 173, Summoner = "HeWhoSlopps", Team = "INT", Opponent = "PTP2", Champion = "Nautalis", Role = "SUP", Kills = 2, Deaths = 6, Assists = 4 },
          new Player { PlayerId = 174, Summoner = "HeWhoSlopps", Team = "INT", Opponent = "TAS2", Champion = "Nautalis", Role = "SUP", Kills = 4, Deaths = 3, Assists = 12 },
          new Player { PlayerId = 175, Summoner = "HeWhoSlopps", Team = "INT", Opponent = "YUP2", Champion = "Zilean", Role = "SUP", Kills = 2, Deaths = 0, Assists = 14 },
          new Player { PlayerId = 176, Summoner = "HeWhoSlopps", Team = "INT", Opponent = "BBZ2", Champion = "Zilean", Role = "SUP", Kills = 3, Deaths = 0, Assists = 16 },
          new Player { PlayerId = 177, Summoner = "HeWhoSlopps", Team = "INT", Opponent = "DD2", Champion = "Nautalis", Role = "SUP", Kills = 0, Deaths = 3, Assists = 14 },
          new Player { PlayerId = 178, Summoner = "HeWhoSlopps", Team = "INT", Opponent = "GURL2", Champion = "Zilean", Role = "SUP", Kills = 0, Deaths = 0, Assists = 18 },
          new Player { PlayerId = 179, Summoner = "fishfishmagish", Team = "INT", Opponent = "DD", Champion = "Renekton", Role = "TOP", Kills = 7, Deaths = 8, Assists = 14 },
          new Player { PlayerId = 180, Summoner = "fishfishmagish", Team = "INT", Opponent = "GURL", Champion = "Sylas", Role = "TOP", Kills = 3, Deaths = 1, Assists = 4 },
          new Player { PlayerId = 181, Summoner = "Pure Llama", Team = "PTP", Opponent = "TAS", Champion = "Kennan", Role = "TOP", Kills = 0, Deaths = 4, Assists = 3 },
          new Player { PlayerId = 182, Summoner = "Pure Llama", Team = "PTP", Opponent = "BBZ", Champion = "Malphite", Role = "TOP", Kills = 7, Deaths = 1, Assists = 10 },
          new Player { PlayerId = 183, Summoner = "Pure Llama", Team = "PTP", Opponent = "DD", Champion = "Malphite", Role = "TOP", Kills = 3, Deaths = 4, Assists = 12 },
          new Player { PlayerId = 184, Summoner = "Pure Llama", Team = "PTP", Opponent = "GURL", Champion = "Darius", Role = "TOP", Kills = 9, Deaths = 5, Assists = 3 },
          new Player { PlayerId = 185, Summoner = "Pure Llama", Team = "PTP", Opponent = "INT2", Champion = "Maoki", Role = "TOP", Kills = 3, Deaths = 0, Assists = 14 },
          new Player { PlayerId = 186, Summoner = "Pure Llama", Team = "PTP", Opponent = "TAS2", Champion = "Maoki", Role = "TOP", Kills = 6, Deaths = 3, Assists = 8 },
          new Player { PlayerId = 187, Summoner = "Pure Llama", Team = "PTP", Opponent = "YUP2", Champion = "Ornn", Role = "TOP", Kills = 4, Deaths = 2, Assists = 4 },
          new Player { PlayerId = 188, Summoner = "Pure Llama", Team = "PTP", Opponent = "BBZ2", Champion = "Maoki", Role = "TOP", Kills = 7, Deaths = 3, Assists = 13 },
          new Player { PlayerId = 189, Summoner = "Pure Llama", Team = "PTP", Opponent = "DD2", Champion = "Mordakaiser", Role = "TOP", Kills = 4, Deaths = 3, Assists = 6 },
          new Player { PlayerId = 190, Summoner = "Pure Llama", Team = "PTP", Opponent = "GURL2", Champion = "Teemo", Role = "TOP", Kills = 5, Deaths = 3, Assists = 5 },
          new Player { PlayerId = 191, Summoner = "Graviel", Team = "PTP", Opponent = "INT", Champion = "Renekton", Role = "TOP", Kills = 1, Deaths = 7, Assists = 5 },
          new Player { PlayerId = 192, Summoner = "Graviel", Team = "PTP", Opponent = "TAS", Champion = "Zac", Role = "JNG", Kills = 3, Deaths = 7, Assists = 1 },
          new Player { PlayerId = 193, Summoner = "Graviel", Team = "PTP", Opponent = "YUP", Champion = "Nocturne", Role = "JNG", Kills = 8, Deaths = 5, Assists = 15 },
          new Player { PlayerId = 194, Summoner = "Graviel", Team = "PTP", Opponent = "BBZ", Champion = "Ashe", Role = "ADC", Kills = 10, Deaths = 4, Assists = 16 },
          new Player { PlayerId = 195, Summoner = "Graviel", Team = "PTP", Opponent = "DD", Champion = "Shen", Role = "JNG", Kills = 3, Deaths = 9, Assists = 15 },
          new Player { PlayerId = 196, Summoner = "Graviel", Team = "PTP", Opponent = "GURL", Champion = "Hecraim", Role = "JNG", Kills = 5, Deaths = 5, Assists = 18 },
          new Player { PlayerId = 197, Summoner = "Graviel", Team = "PTP", Opponent = "INT2", Champion = "Kayn", Role = "JNG", Kills = 6, Deaths = 4, Assists = 14 },
          new Player { PlayerId = 198, Summoner = "Graviel", Team = "PTP", Opponent = "TAS2", Champion = "Hecraim", Role = "JNG", Kills = 9, Deaths = 2, Assists = 7 },
          new Player { PlayerId = 199, Summoner = "Graviel", Team = "PTP", Opponent = "YUP2", Champion = "Kayn", Role = "JNG", Kills = 2, Deaths = 2, Assists = 6 },
          new Player { PlayerId = 200, Summoner = "Graviel", Team = "PTP", Opponent = "BBZ2", Champion = "Hecraim", Role = "JNG", Kills = 6, Deaths = 6, Assists = 18 },
          new Player { PlayerId = 201, Summoner = "Graviel", Team = "PTP", Opponent = "DD2", Champion = "Hecraim", Role = "JNG", Kills = 2, Deaths = 4, Assists = 11 },
          new Player { PlayerId = 202, Summoner = "Graviel", Team = "PTP", Opponent = "GURL2", Champion = "Sejuani", Role = "JNG", Kills = 8, Deaths = 3, Assists = 14 },
          new Player { PlayerId = 203, Summoner = "TheProDH", Team = "PTP", Opponent = "INT", Champion = "Malzahar", Role = "MID", Kills = 2, Deaths = 4, Assists = 3 },
          new Player { PlayerId = 204, Summoner = "TheProDH", Team = "PTP", Opponent = "TAS", Champion = "Viktor", Role = "MID", Kills = 0, Deaths = 5, Assists = 3 },
          new Player { PlayerId = 205, Summoner = "TheProDH", Team = "PTP", Opponent = "YUP", Champion = "Brand", Role = "MID", Kills = 13, Deaths = 6, Assists = 8 },
          new Player { PlayerId = 206, Summoner = "TheProDH", Team = "PTP", Opponent = "BBZ", Champion = "Lilah", Role = "MID", Kills = 8, Deaths = 2, Assists = 17 },
          new Player { PlayerId = 207, Summoner = "TheProDH", Team = "PTP", Opponent = "DD", Champion = "Viktor", Role = "MID", Kills = 7, Deaths = 4, Assists = 10 },
          new Player { PlayerId = 208, Summoner = "TheProDH", Team = "PTP", Opponent = "GURL", Champion = "Lilah", Role = "MID", Kills = 14, Deaths = 3, Assists = 9 },
          new Player { PlayerId = 209, Summoner = "TheProDH", Team = "PTP", Opponent = "INT2", Champion = "Lilah", Role = "MID", Kills = 12, Deaths = 2, Assists = 11 },
          new Player { PlayerId = 210, Summoner = "TheProDH", Team = "PTP", Opponent = "TAS2", Champion = "Malzahar", Role = "MID", Kills = 6, Deaths = 0, Assists = 5 },
          new Player { PlayerId = 211, Summoner = "TheProDH", Team = "PTP", Opponent = "YUP2", Champion = "Veigar", Role = "MID", Kills = 12, Deaths = 1, Assists = 5 },
          new Player { PlayerId = 212, Summoner = "TheProDH", Team = "PTP", Opponent = "BBZ2", Champion = "Lilah", Role = "MID", Kills = 9, Deaths = 0, Assists = 15 },
          new Player { PlayerId = 213, Summoner = "TheProDH", Team = "PTP", Opponent = "GURL2", Champion = "Oriana", Role = "MID", Kills = 6, Deaths = 2, Assists = 13 },
          new Player { PlayerId = 214, Summoner = "Lets-Do-Väynäl", Team = "PTP", Opponent = "INT", Champion = "Jhin", Role = "ADC", Kills = 1, Deaths = 4, Assists = 4 },
          new Player { PlayerId = 215, Summoner = "Lets-Do-Väynäl", Team = "PTP", Opponent = "TAS", Champion = "Jinx", Role = "ADC", Kills = 3, Deaths = 4, Assists = 3 },
          new Player { PlayerId = 216, Summoner = "Lets-Do-Väynäl", Team = "PTP", Opponent = "YUP", Champion = "Jhin", Role = "ADC", Kills = 7, Deaths = 2, Assists = 10 },
          new Player { PlayerId = 217, Summoner = "Lets-Do-Väynäl", Team = "PTP", Opponent = "DD", Champion = "Twitch", Role = "ADC", Kills = 6, Deaths = 7, Assists = 9 },
          new Player { PlayerId = 218, Summoner = "Lets-Do-Väynäl", Team = "PTP", Opponent = "GURL", Champion = "Vayne", Role = "ADC", Kills = 4, Deaths = 3, Assists = 12 },
          new Player { PlayerId = 219, Summoner = "Lets-Do-Väynäl", Team = "PTP", Opponent = "INT2", Champion = "Vayne", Role = "ADC", Kills = 5, Deaths = 2, Assists = 4 },
          new Player { PlayerId = 220, Summoner = "Lets-Do-Väynäl", Team = "PTP", Opponent = "TAS2", Champion = "Senna", Role = "ADC", Kills = 1, Deaths = 4, Assists = 8 },
          new Player { PlayerId = 221, Summoner = "Lets-Do-Väynäl", Team = "PTP", Opponent = "YUP2", Champion = "Vayne", Role = "ADC", Kills = 5, Deaths = 1, Assists = 5 },
          new Player { PlayerId = 222, Summoner = "Lets-Do-Väynäl", Team = "PTP", Opponent = "BBZ2", Champion = "Ahpilios", Role = "ADC", Kills = 6, Deaths = 3, Assists = 7 },
          new Player { PlayerId = 223, Summoner = "Lets-Do-Väynäl", Team = "PTP", Opponent = "DD2", Champion = "Jinx", Role = "ADC", Kills = 6, Deaths = 3, Assists = 9 },
          new Player { PlayerId = 224, Summoner = "Lets-Do-Väynäl", Team = "PTP", Opponent = "GURL2", Champion = "Tristina", Role = "ADC", Kills = 9, Deaths = 2, Assists = 7 },
          new Player { PlayerId = 225, Summoner = "Karrots", Team = "PTP", Opponent = "INT", Champion = "Leona", Role = "SUP", Kills = 0, Deaths = 3, Assists = 4 },
          new Player { PlayerId = 226, Summoner = "Karrots", Team = "PTP", Opponent = "TAS", Champion = "Blitzcrank", Role = "SUP", Kills = 3, Deaths = 3, Assists = 5 },
          new Player { PlayerId = 227, Summoner = "Karrots", Team = "PTP", Opponent = "YUP", Champion = "Morgana", Role = "SUP", Kills = 3, Deaths = 2, Assists = 18 },
          new Player { PlayerId = 228, Summoner = "Karrots", Team = "PTP", Opponent = "BBZ", Champion = "Leona", Role = "SUP", Kills = 0, Deaths = 4, Assists = 23 },
          new Player { PlayerId = 229, Summoner = "Karrots", Team = "PTP", Opponent = "DD", Champion = "Leona", Role = "SUP", Kills = 3, Deaths = 2, Assists = 15 },
          new Player { PlayerId = 230, Summoner = "Karrots", Team = "PTP", Opponent = "GURL", Champion = "Thresh", Role = "SUP", Kills = 4, Deaths = 2, Assists = 15 },
          new Player { PlayerId = 231, Summoner = "Karrots", Team = "PTP", Opponent = "INT2", Champion = "Thresh", Role = "SUP", Kills = 3, Deaths = 2, Assists = 9 },
          new Player { PlayerId = 232, Summoner = "Karrots", Team = "PTP", Opponent = "TAS2", Champion = "Morgana", Role = "SUP", Kills = 0, Deaths = 3, Assists = 8 },
          new Player { PlayerId = 233, Summoner = "Karrots", Team = "PTP", Opponent = "YUP2", Champion = "Thresh", Role = "SUP", Kills = 0, Deaths = 2, Assists = 12 },
          new Player { PlayerId = 234, Summoner = "Karrots", Team = "PTP", Opponent = "BBZ2", Champion = "Braum", Role = "SUP", Kills = 1, Deaths = 3, Assists = 8 },
          new Player { PlayerId = 235, Summoner = "Karrots", Team = "PTP", Opponent = "DD2", Champion = "Malzahar", Role = "MID", Kills = 4, Deaths = 2, Assists = 6 },
          new Player { PlayerId = 236, Summoner = "Karrots", Team = "PTP", Opponent = "GURL2", Champion = "Thresh", Role = "SUP", Kills = 0, Deaths = 2, Assists = 16 },
          new Player { PlayerId = 237, Summoner = "TooMuchDamage", Team = "PTP", Opponent = "INT", Champion = "Graves", Role = "JNG", Kills = 4, Deaths = 7, Assists = 3 },
          new Player { PlayerId = 238, Summoner = "FA7HOM", Team = "PTP", Opponent = "YUP", Champion = "Maoki", Role = "TOP", Kills = 1, Deaths = 3, Assists = 16 },
          new Player { PlayerId = 239, Summoner = "GreyHawk31", Team = "PTP", Opponent = "BBZ", Champion = "Ammumu", Role = "JNG", Kills = 7, Deaths = 2, Assists = 17 },
          new Player { PlayerId = 240, Summoner = "FleshIsAPrision", Team = "PTP", Opponent = "DD2", Champion = "Thresh", Role = "SUP", Kills = 3, Deaths = 3, Assists = 10 },
          new Player { PlayerId = 241, Summoner = "Strawberryyy", Team = "TAS", Opponent = "GURL", Champion = "Camile", Role = "TOP", Kills = 3, Deaths = 5, Assists = 10 },
          new Player { PlayerId = 242, Summoner = "Strawberryyy", Team = "TAS", Opponent = "INT", Champion = "Akali", Role = "TOP", Kills = 3, Deaths = 5, Assists = 1 },
          new Player { PlayerId = 243, Summoner = "Strawberryyy", Team = "TAS", Opponent = "PTP", Champion = "Renekton", Role = "TOP", Kills = 8, Deaths = 1, Assists = 3 },
          new Player { PlayerId = 244, Summoner = "Strawberryyy", Team = "TAS", Opponent = "YUP", Champion = "Kennan", Role = "TOP", Kills = 5, Deaths = 2, Assists = 8 },
          new Player { PlayerId = 245, Summoner = "Strawberryyy", Team = "TAS", Opponent = "BBZ", Champion = "Renekton", Role = "TOP", Kills = 7, Deaths = 2, Assists = 4 },
          new Player { PlayerId = 246, Summoner = "Strawberryyy", Team = "TAS", Opponent = "DD", Champion = "Wu-kong", Role = "TOP", Kills = 7, Deaths = 0, Assists = 9 },
          new Player { PlayerId = 247, Summoner = "Strawberryyy", Team = "TAS", Opponent = "GURL2", Champion = "Wu-kong", Role = "TOP", Kills = 11, Deaths = 2, Assists = 10 },
          new Player { PlayerId = 248, Summoner = "Strawberryyy", Team = "TAS", Opponent = "INT2", Champion = "Wu-kong", Role = "TOP", Kills = 6, Deaths = 5, Assists = 8 },
          new Player { PlayerId = 249, Summoner = "Strawberryyy", Team = "TAS", Opponent = "PTP2", Champion = "Jayce", Role = "TOP", Kills = 4, Deaths = 6, Assists = 3 },
          new Player { PlayerId = 250, Summoner = "Strawberryyy", Team = "TAS", Opponent = "YUP2", Champion = "Gnar", Role = "TOP", Kills = 2, Deaths = 2, Assists = 9 },
          new Player { PlayerId = 251, Summoner = "Strawberryyy", Team = "TAS", Opponent = "BBZ2", Champion = "Aatrox", Role = "TOP", Kills = 3, Deaths = 3, Assists = 7 },
          new Player { PlayerId = 252, Summoner = "Strawberryyy", Team = "TAS", Opponent = "DD2", Champion = "Sett", Role = "TOP", Kills = 6, Deaths = 2, Assists = 6 },
          new Player { PlayerId = 253, Summoner = "Yoniee", Team = "TAS", Opponent = "PTP", Champion = "Kha'zix", Role = "JNG", Kills = 13, Deaths = 2, Assists = 5 },
          new Player { PlayerId = 254, Summoner = "Yoniee", Team = "TAS", Opponent = "YUP", Champion = "Kha'zix", Role = "JNG", Kills = 4, Deaths = 1, Assists = 7 },
          new Player { PlayerId = 255, Summoner = "Yoniee", Team = "TAS", Opponent = "BBZ", Champion = "Oriana", Role = "MID", Kills = 7, Deaths = 2, Assists = 8 },
          new Player { PlayerId = 256, Summoner = "Yoniee", Team = "TAS", Opponent = "DD", Champion = "Twisted-fate", Role = "MID", Kills = 9, Deaths = 1, Assists = 3 },
          new Player { PlayerId = 257, Summoner = "Yoniee", Team = "TAS", Opponent = "GURL2", Champion = "Fiddlesticks", Role = "JNG", Kills = 7, Deaths = 6, Assists = 12 },
          new Player { PlayerId = 258, Summoner = "Yoniee", Team = "TAS", Opponent = "INT2", Champion = "Vladamir", Role = "MID", Kills = 2, Deaths = 5, Assists = 5 },
          new Player { PlayerId = 259, Summoner = "Yoniee", Team = "TAS", Opponent = "PTP2", Champion = "Ezreal", Role = "ADC", Kills = 1, Deaths = 5, Assists = 6 },
          new Player { PlayerId = 260, Summoner = "Yoniee", Team = "TAS", Opponent = "YUP2", Champion = "Gragas", Role = "JNG", Kills = 4, Deaths = 1, Assists = 10 },
          new Player { PlayerId = 261, Summoner = "Yoniee", Team = "TAS", Opponent = "BBZ2", Champion = "Shyvana", Role = "JNG", Kills = 7, Deaths = 2, Assists = 13 },
          new Player { PlayerId = 262, Summoner = "Yoniee", Team = "TAS", Opponent = "DD2", Champion = "Poppy", Role = "JNG", Kills = 2, Deaths = 6, Assists = 19 },
          new Player { PlayerId = 263, Summoner = "Hismee", Team = "TAS", Opponent = "GURL", Champion = "Neeko", Role = "MID", Kills = 4, Deaths = 4, Assists = 7 },
          new Player { PlayerId = 264, Summoner = "Hismee", Team = "TAS", Opponent = "INT", Champion = "Oriana", Role = "MID", Kills = 2, Deaths = 7, Assists = 3 },
          new Player { PlayerId = 265, Summoner = "Hismee", Team = "TAS", Opponent = "PTP", Champion = "Malphite", Role = "MID", Kills = 0, Deaths = 1, Assists = 10 },
          new Player { PlayerId = 266, Summoner = "Hismee", Team = "TAS", Opponent = "YUP", Champion = "Oriana", Role = "MID", Kills = 6, Deaths = 1, Assists = 10 },
          new Player { PlayerId = 267, Summoner = "Hismee", Team = "TAS", Opponent = "BBZ", Champion = "Shyvana", Role = "JNG", Kills = 6, Deaths = 1, Assists = 9 },
          new Player { PlayerId = 268, Summoner = "Hismee", Team = "TAS", Opponent = "GURL2", Champion = "Malzhar", Role = "MID", Kills = 6, Deaths = 6, Assists = 15 },
          new Player { PlayerId = 269, Summoner = "Hismee", Team = "TAS", Opponent = "PTP2", Champion = "Sejuani", Role = "JNG", Kills = 3, Deaths = 3, Assists = 6 },
          new Player { PlayerId = 270, Summoner = "Hismee", Team = "TAS", Opponent = "YUP2", Champion = "Oriana", Role = "MID", Kills = 8, Deaths = 3, Assists = 5 },
          new Player { PlayerId = 271, Summoner = "Gùa", Team = "TAS", Opponent = "GURL", Champion = "Lucian", Role = "ADC", Kills = 9, Deaths = 4, Assists = 6 },
          new Player { PlayerId = 272, Summoner = "Gùa", Team = "TAS", Opponent = "INT", Champion = "Lucian", Role = "ADC", Kills = 3, Deaths = 7, Assists = 6 },
          new Player { PlayerId = 273, Summoner = "Gùa", Team = "TAS", Opponent = "PTP", Champion = "Tristina", Role = "ADC", Kills = 1, Deaths = 3, Assists = 4 },
          new Player { PlayerId = 274, Summoner = "Gùa", Team = "TAS", Opponent = "YUP", Champion = "Yauso", Role = "ADC", Kills = 5, Deaths = 2, Assists = 1 },
          new Player { PlayerId = 275, Summoner = "Gùa", Team = "TAS", Opponent = "BBZ", Champion = "Lucian", Role = "ADC", Kills = 5, Deaths = 3, Assists = 7 },
          new Player { PlayerId = 276, Summoner = "Gùa", Team = "TAS", Opponent = "DD", Champion = "Tristina", Role = "ADC", Kills = 5, Deaths = 2, Assists = 13 },
          new Player { PlayerId = 277, Summoner = "Gùa", Team = "TAS", Opponent = "GURL2", Champion = "Lucian", Role = "ADC", Kills = 8, Deaths = 7, Assists = 11 },
          new Player { PlayerId = 278, Summoner = "Gùa", Team = "TAS", Opponent = "INT2", Champion = "Kalista", Role = "ADC", Kills = 5, Deaths = 6, Assists = 4 },
          new Player { PlayerId = 279, Summoner = "Gùa", Team = "TAS", Opponent = "YUP2", Champion = "Tristina", Role = "ADC", Kills = 14, Deaths = 2, Assists = 11 },
          new Player { PlayerId = 280, Summoner = "Gùa", Team = "TAS", Opponent = "BBZ2", Champion = "Yauso", Role = "ADC", Kills = 10, Deaths = 4, Assists = 7 },
          new Player { PlayerId = 281, Summoner = "Gùa", Team = "TAS", Opponent = "DD2", Champion = "Kai'sa", Role = "ADC", Kills = 16, Deaths = 6, Assists = 9 },
          new Player { PlayerId = 282, Summoner = "Anh Bo Bùng Binh", Team = "TAS", Opponent = "GURL", Champion = "Galio", Role = "SUP", Kills = 3, Deaths = 4, Assists = 10 },
          new Player { PlayerId = 283, Summoner = "Anh Bo Bùng Binh", Team = "TAS", Opponent = "INT", Champion = "Pantheon", Role = "SUP", Kills = 1, Deaths = 7, Assists = 5 },
          new Player { PlayerId = 284, Summoner = "Anh Bo Bùng Binh", Team = "TAS", Opponent = "PTP", Champion = "Galio", Role = "SUP", Kills = 1, Deaths = 2, Assists = 6 },
          new Player { PlayerId = 285, Summoner = "Anh Bo Bùng Binh", Team = "TAS", Opponent = "YUP", Champion = "Alistar", Role = "SUP", Kills = 0, Deaths = 4, Assists = 13 },
          new Player { PlayerId = 286, Summoner = "Anh Bo Bùng Binh", Team = "TAS", Opponent = "BBZ", Champion = "Thresh", Role = "SUP", Kills = 0, Deaths = 3, Assists = 15 },
          new Player { PlayerId = 287, Summoner = "Anh Bo Bùng Binh", Team = "TAS", Opponent = "DD", Champion = "Leona", Role = "SUP", Kills = 2, Deaths = 1, Assists = 16 },
          new Player { PlayerId = 288, Summoner = "Anh Bo Bùng Binh", Team = "TAS", Opponent = "GURL2", Champion = "Leona", Role = "SUP", Kills = 4, Deaths = 7, Assists = 16 },
          new Player { PlayerId = 289, Summoner = "Anh Bo Bùng Binh", Team = "TAS", Opponent = "INT2", Champion = "Thresh", Role = "SUP", Kills = 1, Deaths = 5, Assists = 10 },
          new Player { PlayerId = 290, Summoner = "Anh Bo Bùng Binh", Team = "TAS", Opponent = "PTP2", Champion = "Soraka", Role = "SUP", Kills = 1, Deaths = 5, Assists = 7 },
          new Player { PlayerId = 291, Summoner = "Anh Bo Bùng Binh", Team = "TAS", Opponent = "YUP2", Champion = "Alistar", Role = "SUP", Kills = 0, Deaths = 2, Assists = 13 },
          new Player { PlayerId = 292, Summoner = "Anh Bo Bùng Binh", Team = "TAS", Opponent = "BBZ2", Champion = "Blitzcrank", Role = "SUP", Kills = 1, Deaths = 5, Assists = 17 },
          new Player { PlayerId = 293, Summoner = "Anh Bo Bùng Binh", Team = "TAS", Opponent = "DD2", Champion = "Swain", Role = "SUP", Kills = 3, Deaths = 5, Assists = 19 },
          new Player { PlayerId = 294, Summoner = "Voltox", Team = "TAS", Opponent = "GURL", Champion = "Master-yi", Role = "JNG", Kills = 8, Deaths = 8, Assists = 9 },
          new Player { PlayerId = 295, Summoner = "Voltox", Team = "TAS", Opponent = "GURL", Champion = "Zac", Role = "JNG", Kills = 2, Deaths = 5, Assists = 8 },
          new Player { PlayerId = 296, Summoner = "Trash Zero", Team = "TAS", Opponent = "DD", Champion = "Kayn", Role = "JNG", Kills = 9, Deaths = 2, Assists = 5 },
          new Player { PlayerId = 297, Summoner = "Trash Zero", Team = "TAS", Opponent = "INT2", Champion = "Jax", Role = "JNG", Kills = 4, Deaths = 5, Assists = 6 },
          new Player { PlayerId = 298, Summoner = "Trash Zero", Team = "TAS", Opponent = "PTP2", Champion = "Vladamir", Role = "MID", Kills = 3, Deaths = 3, Assists = 3 },
          new Player { PlayerId = 299, Summoner = "Trash Zero", Team = "TAS", Opponent = "BBZ2", Champion = "Kayle", Role = "MID", Kills = 1, Deaths = 5, Assists = 9 },
          new Player { PlayerId = 300, Summoner = "Trash Zero", Team = "TAS", Opponent = "DD2", Champion = "Ryze", Role = "MID", Kills = 8, Deaths = 5, Assists = 14 },
          new Player { PlayerId = 301, Summoner = "SmoothMoves", Team = "YUP", Opponent = "DD", Champion = "Lulu", Role = "SUP", Kills = 1, Deaths = 5, Assists = 15 },
          new Player { PlayerId = 302, Summoner = "SmoothMoves", Team = "YUP", Opponent = "GURL", Champion = "Lulu", Role = "SUP", Kills = 1, Deaths = 3, Assists = 21 },
          new Player { PlayerId = 303, Summoner = "SmoothMoves", Team = "YUP", Opponent = "INT", Champion = "Janna", Role = "SUP", Kills = 0, Deaths = 3, Assists = 1 },
          new Player { PlayerId = 304, Summoner = "SmoothMoves", Team = "YUP", Opponent = "PTP", Champion = "Nami", Role = "SUP", Kills = 1, Deaths = 6, Assists = 10 },
          new Player { PlayerId = 305, Summoner = "SmoothMoves", Team = "YUP", Opponent = "TAS", Champion = "Shen", Role = "TOP", Kills = 0, Deaths = 4, Assists = 5 },
          new Player { PlayerId = 306, Summoner = "SmoothMoves", Team = "YUP", Opponent = "BBZ", Champion = "Yorick", Role = "TOP", Kills = 3, Deaths = 8, Assists = 1 },
          new Player { PlayerId = 307, Summoner = "SmoothMoves", Team = "YUP", Opponent = "DD2", Champion = "Yorick", Role = "TOP", Kills = 0, Deaths = 1, Assists = 1 },
          new Player { PlayerId = 308, Summoner = "SmoothMoves", Team = "YUP", Opponent = "GURL2", Champion = "Yorick", Role = "TOP", Kills = 2, Deaths = 9, Assists = 7 },
          new Player { PlayerId = 309, Summoner = "SmoothMoves", Team = "YUP", Opponent = "INT2", Champion = "Shen", Role = "TOP", Kills = 0, Deaths = 6, Assists = 3 },
          new Player { PlayerId = 310, Summoner = "SmoothMoves", Team = "YUP", Opponent = "PTP2", Champion = "Shen", Role = "TOP", Kills = 0, Deaths = 6, Assists = 3 },
          new Player { PlayerId = 311, Summoner = "SmoothMoves", Team = "YUP", Opponent = "TAS2", Champion = "illoai", Role = "TOP", Kills = 3, Deaths = 7, Assists = 2 },
          new Player { PlayerId = 312, Summoner = "SmoothMoves", Team = "YUP", Opponent = "BBZ2", Champion = "Nasus", Role = "TOP", Kills = 1, Deaths = 3, Assists = 3 },
          new Player { PlayerId = 313, Summoner = "UltMilesMorales", Team = "YUP", Opponent = "DD", Champion = "Poppy", Role = "TOP", Kills = 2, Deaths = 5, Assists = 7 },
          new Player { PlayerId = 314, Summoner = "UltMilesMorales", Team = "YUP", Opponent = "GURL", Champion = "Gnar", Role = "TOP", Kills = 1, Deaths = 6, Assists = 10 },
          new Player { PlayerId = 315, Summoner = "UltMilesMorales", Team = "YUP", Opponent = "INT", Champion = "Neeko", Role = "MID", Kills = 1, Deaths = 2, Assists = 0 },
          new Player { PlayerId = 316, Summoner = "Connection-Error", Team = "YUP", Opponent = "DD", Champion = "Tristina", Role = "ADC", Kills = 11, Deaths = 8, Assists = 5 },
          new Player { PlayerId = 317, Summoner = "Connection-Error", Team = "YUP", Opponent = "TAS", Champion = "Ekko", Role = "MID", Kills = 4, Deaths = 4, Assists = 1 },
          new Player { PlayerId = 318, Summoner = "Connection-Error", Team = "YUP", Opponent = "BBZ", Champion = "Yummi", Role = "SUP", Kills = 1, Deaths = 4, Assists = 10 },
          new Player { PlayerId = 319, Summoner = "Connection-Error", Team = "YUP", Opponent = "DD2", Champion = "Yummi", Role = "SUP", Kills = 0, Deaths = 0, Assists = 11 },
          new Player { PlayerId = 320, Summoner = "Connection-Error", Team = "YUP", Opponent = "GURL2", Champion = "Yummi", Role = "SUP", Kills = 1, Deaths = 4, Assists = 23 },
          new Player { PlayerId = 321, Summoner = "Connection-Error", Team = "YUP", Opponent = "INT2", Champion = "Yummi", Role = "SUP", Kills = 0, Deaths = 3, Assists = 3 },
          new Player { PlayerId = 322, Summoner = "Connection-Error", Team = "YUP", Opponent = "PTP2", Champion = "Morgana", Role = "SUP", Kills = 1, Deaths = 5, Assists = 4 },
          new Player { PlayerId = 323, Summoner = "OnceWeak", Team = "YUP", Opponent = "DD", Champion = "Oriana", Role = "MID", Kills = 3, Deaths = 4, Assists = 11 },
          new Player { PlayerId = 324, Summoner = "OnceWeak", Team = "YUP", Opponent = "GURL", Champion = "Galio", Role = "MID", Kills = 3, Deaths = 9, Assists = 11 },
          new Player { PlayerId = 325, Summoner = "OnceWeak", Team = "YUP", Opponent = "INT", Champion = "Sejuani", Role = "JNG", Kills = 0, Deaths = 3, Assists = 0 },
          new Player { PlayerId = 326, Summoner = "OnceWeak", Team = "YUP", Opponent = "PTP", Champion = "Olaf", Role = "JNG", Kills = 5, Deaths = 7, Assists = 10 },
          new Player { PlayerId = 327, Summoner = "OnceWeak", Team = "YUP", Opponent = "TAS", Champion = "Ashe", Role = "ADC", Kills = 1, Deaths = 4, Assists = 5 },
          new Player { PlayerId = 328, Summoner = "OnceWeak", Team = "YUP", Opponent = "BBZ", Champion = "Jarvan-IV", Role = "JNG", Kills = 0, Deaths = 4, Assists = 11 },
          new Player { PlayerId = 329, Summoner = "OnceWeak", Team = "YUP", Opponent = "DD2", Champion = "Hecraim", Role = "JNG", Kills = 4, Deaths = 1, Assists = 8 },
          new Player { PlayerId = 330, Summoner = "OnceWeak", Team = "YUP", Opponent = "GURL2", Champion = "Hecraim", Role = "JNG", Kills = 3, Deaths = 5, Assists = 12 },
          new Player { PlayerId = 331, Summoner = "OnceWeak", Team = "YUP", Opponent = "INT2", Champion = "Sett", Role = "JNG", Kills = 0, Deaths = 5, Assists = 2 },
          new Player { PlayerId = 332, Summoner = "OnceWeak", Team = "YUP", Opponent = "BBZ2", Champion = "Olaf", Role = "JNG", Kills = 2, Deaths = 5, Assists = 5 },
          new Player { PlayerId = 333, Summoner = "5picy1cey", Team = "YUP", Opponent = "DD", Champion = "Diana", Role = "JNG", Kills = 5, Deaths = 7, Assists = 11 },
          new Player { PlayerId = 334, Summoner = "5picy1cey", Team = "YUP", Opponent = "GURL", Champion = "Elise", Role = "JNG", Kills = 7, Deaths = 5, Assists = 12 },
          new Player { PlayerId = 335, Summoner = "5picy1cey", Team = "YUP", Opponent = "INT", Champion = "Mordakaiser", Role = "TOP", Kills = 0, Deaths = 6, Assists = 1 },
          new Player { PlayerId = 336, Summoner = "5picy1cey", Team = "YUP", Opponent = "PTP", Champion = "Lissandra", Role = "TOP", Kills = 2, Deaths = 9, Assists = 4 },
          new Player { PlayerId = 337, Summoner = "5picy1cey", Team = "YUP", Opponent = "TAS", Champion = "Leona", Role = "SUP", Kills = 1, Deaths = 3, Assists = 6 },
          new Player { PlayerId = 338, Summoner = "5picy1cey", Team = "YUP", Opponent = "GURL2", Champion = "Lissandra", Role = "MID", Kills = 9, Deaths = 6, Assists = 11 },
          new Player { PlayerId = 339, Summoner = "5picy1cey", Team = "YUP", Opponent = "PTP2", Champion = "Lux", Role = "MID", Kills = 5, Deaths = 3, Assists = 1 },
          new Player { PlayerId = 340, Summoner = "5picy1cey", Team = "YUP", Opponent = "TAS2", Champion = "Zyra", Role = "SUP", Kills = 2, Deaths = 4, Assists = 3 },
          new Player { PlayerId = 341, Summoner = "5picy1cey", Team = "YUP", Opponent = "BBZ2", Champion = "Zilean", Role = "SUP", Kills = 1, Deaths = 2, Assists = 12 },
          new Player { PlayerId = 342, Summoner = "XTurtleOfDoomX", Team = "YUP", Opponent = "GURL", Champion = "Varus", Role = "ADC", Kills = 11, Deaths = 4, Assists = 10 },
          new Player { PlayerId = 343, Summoner = "XTurtleOfDoomX", Team = "YUP", Opponent = "INT", Champion = "Sivir", Role = "ADC", Kills = 0, Deaths = 3, Assists = 0 },
          new Player { PlayerId = 344, Summoner = "XTurtleOfDoomX", Team = "YUP", Opponent = "PTP", Champion = "Ashe", Role = "ADC", Kills = 5, Deaths = 5, Assists = 7 },
          new Player { PlayerId = 345, Summoner = "XTurtleOfDoomX", Team = "YUP", Opponent = "BBZ", Champion = "Caitlyn", Role = "ADC", Kills = 7, Deaths = 1, Assists = 3 },
          new Player { PlayerId = 346, Summoner = "XTurtleOfDoomX", Team = "YUP", Opponent = "DD2", Champion = "Caitlyn", Role = "ADC", Kills = 4, Deaths = 0, Assists = 4 },
          new Player { PlayerId = 347, Summoner = "XTurtleOfDoomX", Team = "YUP", Opponent = "GURL2", Champion = "Ashe", Role = "ADC", Kills = 14, Deaths = 4, Assists = 10 },
          new Player { PlayerId = 348, Summoner = "XTurtleOfDoomX", Team = "YUP", Opponent = "INT2", Champion = "Caitlyn", Role = "ADC", Kills = 2, Deaths = 3, Assists = 1 },
          new Player { PlayerId = 349, Summoner = "XTurtleOfDoomX", Team = "YUP", Opponent = "PTP2", Champion = "Lucian", Role = "ADC", Kills = 1, Deaths = 5, Assists = 2 },
          new Player { PlayerId = 350, Summoner = "XTurtleOfDoomX", Team = "YUP", Opponent = "TAS2", Champion = "Ashe", Role = "ADC", Kills = 2, Deaths = 5, Assists = 5 },
          new Player { PlayerId = 351, Summoner = "XTurtleOfDoomX", Team = "YUP", Opponent = "BBZ2", Champion = "Ashe", Role = "ADC", Kills = 5, Deaths = 1, Assists = 7 },
          new Player { PlayerId = 352, Summoner = "EliteStrike", Team = "YUP", Opponent = "BBZ", Champion = "Ekko", Role = "MID", Kills = 8, Deaths = 5, Assists = 3 },
          new Player { PlayerId = 353, Summoner = "EliteStrike", Team = "YUP", Opponent = "DD2", Champion = "Ekko", Role = "MID", Kills = 8, Deaths = 1, Assists = 7 },
          new Player { PlayerId = 354, Summoner = "EliteStrike", Team = "YUP", Opponent = "INT2", Champion = "Azir", Role = "MID", Kills = 2, Deaths = 3, Assists = 1 },
          new Player { PlayerId = 355, Summoner = "EliteStrike", Team = "YUP", Opponent = "TAS2", Champion = "Ekko", Role = "MID", Kills = 3, Deaths = 8, Assists = 4 },
          new Player { PlayerId = 356, Summoner = "EliteStrike", Team = "YUP", Opponent = "BBZ2", Champion = "Akali", Role = "MID", Kills = 7, Deaths = 2, Assists = 5 },
          new Player { PlayerId = 357, Summoner = "EliteStrike", Team = "YUP", Opponent = "BBZ", Champion = "Ekko", Role = "MID", Kills = 8, Deaths = 5, Assists = 3 },
          new Player { PlayerId = 358, Summoner = "Savedbytheaj", Team = "YUP", Opponent = "PTP", Champion = "Akali", Role = "MID", Kills = 5, Deaths = 5, Assists = 6 },
          new Player { PlayerId = 359, Summoner = "Savedbytheaj", Team = "YUP", Opponent = "TAS", Champion = "Lee-sin", Role = "JNG", Kills = 4, Deaths = 5, Assists = 2 },
          new Player { PlayerId = 360, Summoner = "Savedbytheaj", Team = "YUP", Opponent = "TAS2", Champion = "Sett", Role = "JNG", Kills = 0, Deaths = 4, Assists = 3 },
          new Player { PlayerId = 361, Summoner = "LPelican", Team = "DD", Opponent = "INT", Champion = "Kayn", Role = "JNG", Kills = 6, Deaths = 8, Assists = 13 },
          new Player { PlayerId = 362, Summoner = "Teaamoe", Team = "DD", Opponent = "YUP", Champion = "Dr.Mundo", Role = "TOP", Kills = 5, Deaths = 3, Assists = 9 },
          new Player { PlayerId = 363, Summoner = "Teaamoe", Team = "DD", Opponent = "YUP2", Champion = "Shen", Role = "TOP", Kills = 2, Deaths = 2, Assists = 0 },
          new Player { PlayerId = 364, Summoner = "Teaamoe", Team = "DD", Opponent = "BBZ2", Champion = "Urgot", Role = "TOP", Kills = 3, Deaths = 5, Assists = 2 },
          new Player { PlayerId = 365, Summoner = "Teaamoe", Team = "DD", Opponent = "GURL2", Champion = "Shen", Role = "TOP", Kills = 3, Deaths = 2, Assists = 17 },
          new Player { PlayerId = 366, Summoner = "Teaamoe", Team = "DD", Opponent = "INT2", Champion = "Shen", Role = "TOP", Kills = 2, Deaths = 1, Assists = 7 },
          new Player { PlayerId = 367, Summoner = "Teaamoe", Team = "DD", Opponent = "DD2", Champion = "Shen", Role = "TOP", Kills = 0, Deaths = 3, Assists = 8 },
          new Player { PlayerId = 368, Summoner = "Teaamoe", Team = "DD", Opponent = "TAS2", Champion = "Shen", Role = "TOP", Kills = 3, Deaths = 7, Assists = 11 },
          new Player { PlayerId = 369, Summoner = "6EtHaNoS9", Team = "DD", Opponent = "YUP", Champion = "Morgana", Role = "SUP", Kills = 2, Deaths = 4, Assists = 16 },
          new Player { PlayerId = 370, Summoner = "6EtHaNoS9", Team = "DD", Opponent = "BBZ", Champion = "Lulu", Role = "SUP", Kills = 0, Deaths = 4, Assists = 1 },
          new Player { PlayerId = 371, Summoner = "6EtHaNoS9", Team = "DD", Opponent = "GURL", Champion = "Nautalis", Role = "SUP", Kills = 0, Deaths = 9, Assists = 8 },
          new Player { PlayerId = 372, Summoner = "6EtHaNoS9", Team = "DD", Opponent = "INT", Champion = "Leona", Role = "SUP", Kills = 1, Deaths = 9, Assists = 22 },
          new Player { PlayerId = 373, Summoner = "6EtHaNoS9", Team = "DD", Opponent = "PTP", Champion = "Rakan", Role = "SUP", Kills = 1, Deaths = 5, Assists = 16 },
          new Player { PlayerId = 374, Summoner = "6EtHaNoS9", Team = "DD", Opponent = "TAS", Champion = "Nautalis", Role = "SUP", Kills = 1, Deaths = 5, Assists = 3 },
          new Player { PlayerId = 375, Summoner = "6EtHaNoS9", Team = "DD", Opponent = "YUP2", Champion = "Morgana", Role = "SUP", Kills = 0, Deaths = 3, Assists = 0 },
          new Player { PlayerId = 376, Summoner = "6EtHaNoS9", Team = "DD", Opponent = "BBZ2", Champion = "Leona", Role = "SUP", Kills = 0, Deaths = 7, Assists = 3 },
          new Player { PlayerId = 377, Summoner = "6EtHaNoS9", Team = "DD", Opponent = "GURL2", Champion = "Alistar", Role = "SUP", Kills = 1, Deaths = 2, Assists = 19 },
          new Player { PlayerId = 378, Summoner = "6EtHaNoS9", Team = "DD", Opponent = "INT2", Champion = "Alistar", Role = "SUP", Kills = 0, Deaths = 6, Assists = 3 },
          new Player { PlayerId = 379, Summoner = "6EtHaNoS9", Team = "DD", Opponent = "PTP2", Champion = "Galio", Role = "SUP", Kills = 1, Deaths = 4, Assists = 8 },
          new Player { PlayerId = 380, Summoner = "6EtHaNoS9", Team = "DD", Opponent = "TAS2", Champion = "Alistar", Role = "SUP", Kills = 1, Deaths = 10, Assists = 16 },
          new Player { PlayerId = 381, Summoner = "Epic-Gaymes", Team = "DD", Opponent = "YUP", Champion = "Olaf", Role = "JNG", Kills = 1, Deaths = 6, Assists = 10 },
          new Player { PlayerId = 382, Summoner = "Epic-Gaymes", Team = "DD", Opponent = "BBZ", Champion = "Kha'zix", Role = "JNG", Kills = 1, Deaths = 3, Assists = 10 },
          new Player { PlayerId = 383, Summoner = "Epic-Gaymes", Team = "DD", Opponent = "GURL", Champion = "Hecraim", Role = "JNG", Kills = 3, Deaths = 5, Assists = 6 },
          new Player { PlayerId = 384, Summoner = "Epic-Gaymes", Team = "DD", Opponent = "PTP", Champion = "Hecraim", Role = "JNG", Kills = 3, Deaths = 6, Assists = 12 },
          new Player { PlayerId = 385, Summoner = "Epic-Gaymes", Team = "DD", Opponent = "TAS", Champion = "Hecraim", Role = "JNG", Kills = 0, Deaths = 6, Assists = 5 },
          new Player { PlayerId = 386, Summoner = "Epic-Gaymes", Team = "DD", Opponent = "YUP2", Champion = "Olaf", Role = "JNG", Kills = 0, Deaths = 5, Assists = 2 },
          new Player { PlayerId = 387, Summoner = "Epic-Gaymes", Team = "DD", Opponent = "BBZ2", Champion = "Jhin", Role = "ADC", Kills = 2, Deaths = 5, Assists = 5 },
          new Player { PlayerId = 388, Summoner = "Epic-Gaymes", Team = "DD", Opponent = "GURL2", Champion = "Jhin", Role = "ADC", Kills = 9, Deaths = 2, Assists = 12 },
          new Player { PlayerId = 389, Summoner = "Epic-Gaymes", Team = "DD", Opponent = "PTP2", Champion = "Jhin", Role = "ADC", Kills = 1, Deaths = 5, Assists = 2 },
          new Player { PlayerId = 390, Summoner = "Epic-Gaymes", Team = "DD", Opponent = "TAS2", Champion = "Jhin", Role = "ADC", Kills = 6, Deaths = 5, Assists = 11 },
          new Player { PlayerId = 391, Summoner = "Lyhtz", Team = "DD", Opponent = "YUP", Champion = "Vladamir", Role = "MID", Kills = 6, Deaths = 5, Assists = 10 },
          new Player { PlayerId = 392, Summoner = "Lyhtz", Team = "DD", Opponent = "BBZ", Champion = "Kayle", Role = "TOP", Kills = 3, Deaths = 3, Assists = 1 },
          new Player { PlayerId = 393, Summoner = "Lyhtz", Team = "DD", Opponent = "GURL", Champion = "Jinx", Role = "ADC", Kills = 8, Deaths = 7, Assists = 4 },
          new Player { PlayerId = 394, Summoner = "Lyhtz", Team = "DD", Opponent = "INT", Champion = "Jinx", Role = "ADC", Kills = 14, Deaths = 6, Assists = 11 },
          new Player { PlayerId = 395, Summoner = "Lyhtz", Team = "DD", Opponent = "PTP", Champion = "Xayah", Role = "ADC", Kills = 6, Deaths = 3, Assists = 11 },
          new Player { PlayerId = 396, Summoner = "Lyhtz", Team = "DD", Opponent = "TAS", Champion = "Jinx", Role = "ADC", Kills = 2, Deaths = 6, Assists = 3 },
          new Player { PlayerId = 397, Summoner = "Lyhtz", Team = "DD", Opponent = "YUP2", Champion = "Ashe", Role = "ADC", Kills = 1, Deaths = 3, Assists = 1 },
          new Player { PlayerId = 398, Summoner = "Lyhtz", Team = "DD", Opponent = "BBZ2", Champion = "Vladamir", Role = "MID", Kills = 4, Deaths = 4, Assists = 2 },
          new Player { PlayerId = 399, Summoner = "Lyhtz", Team = "DD", Opponent = "GURL2", Champion = "Hecraim", Role = "JNG", Kills = 11, Deaths = 3, Assists = 13 },
          new Player { PlayerId = 400, Summoner = "Lyhtz", Team = "DD", Opponent = "INT2", Champion = "Kayn", Role = "JNG", Kills = 7, Deaths = 5, Assists = 6 },
          new Player { PlayerId = 401, Summoner = "Lyhtz", Team = "DD", Opponent = "PTP2", Champion = "Kayn", Role = "JNG", Kills = 9, Deaths = 5, Assists = 5 },
          new Player { PlayerId = 402, Summoner = "Lyhtz", Team = "DD", Opponent = "TAS2", Champion = "Kayn", Role = "JNG", Kills = 4, Deaths = 7, Assists = 11 },
          new Player { PlayerId = 403, Summoner = "Smaafu", Team = "DD", Opponent = "BBZ", Champion = "Galio", Role = "MID", Kills = 0, Deaths = 2, Assists = 3 },
          new Player { PlayerId = 404, Summoner = "Smaafu", Team = "DD", Opponent = "GURL", Champion = "Dr.Mundo", Role = "TOP", Kills = 1, Deaths = 7, Assists = 6 },
          new Player { PlayerId = 405, Summoner = "Smaafu", Team = "DD", Opponent = "INT", Champion = "Yorick", Role = "TOP", Kills = 11, Deaths = 5, Assists = 13 },
          new Player { PlayerId = 406, Summoner = "Smaafu", Team = "DD", Opponent = "PTP", Champion = "Mordakaiser", Role = "TOP", Kills = 5, Deaths = 4, Assists = 9 },
          new Player { PlayerId = 407, Summoner = "Smaafu", Team = "DD", Opponent = "TAS", Champion = "Fiora", Role = "TOP", Kills = 0, Deaths = 5, Assists = 2 },
          new Player { PlayerId = 408, Summoner = "Smaafu", Team = "DD", Opponent = "BBZ2", Champion = "Vi", Role = "JNG", Kills = 0, Deaths = 8, Assists = 3 },
          new Player { PlayerId = 409, Summoner = "Smaafu", Team = "DD", Opponent = "GURL2", Champion = "Rumble", Role = "MID", Kills = 7, Deaths = 3, Assists = 12 },
          new Player { PlayerId = 410, Summoner = "Smaafu", Team = "DD", Opponent = "INT2", Champion = "Oriana", Role = "MID", Kills = 4, Deaths = 4, Assists = 6 },
          new Player { PlayerId = 411, Summoner = "Smaafu", Team = "DD", Opponent = "PTP2", Champion = "Rumble", Role = "MID", Kills = 4, Deaths = 2, Assists = 8 },
          new Player { PlayerId = 412, Summoner = "Smaafu", Team = "DD", Opponent = "TAS2", Champion = "Rumble", Role = "MID", Kills = 10, Deaths = 6, Assists = 9 },
          new Player { PlayerId = 413, Summoner = "DD-ON-TOP-XDDDDD", Team = "DD", Opponent = "YUP", Champion = "Caitlyn", Role = "ADC", Kills = 15, Deaths = 4, Assists = 5 },
          new Player { PlayerId = 414, Summoner = "DD-ON-TOP-XDDDDD", Team = "DD", Opponent = "BBZ", Champion = "Ashe", Role = "ADC", Kills = 1, Deaths = 3, Assists = 1 },
          new Player { PlayerId = 415, Summoner = "DD-ON-TOP-XDDDDD", Team = "DD", Opponent = "GURL", Champion = "Kassadin", Role = "MID", Kills = 4, Deaths = 4, Assists = 9 },
          new Player { PlayerId = 416, Summoner = "DD-ON-TOP-XDDDDD", Team = "DD", Opponent = "INT", Champion = "Vladamir", Role = "MID", Kills = 8, Deaths = 4, Assists = 16 },
          new Player { PlayerId = 417, Summoner = "DD-ON-TOP-XDDDDD", Team = "DD", Opponent = "PTP", Champion = "Vladamir", Role = "MID", Kills = 11, Deaths = 4, Assists = 9 },
          new Player { PlayerId = 418, Summoner = "DD-ON-TOP-XDDDDD", Team = "DD", Opponent = "TAS", Champion = "Kassadin", Role = "MID", Kills = 3, Deaths = 10, Assists = 2 },
          new Player { PlayerId = 419, Summoner = "DD-ON-TOP-XDDDDD", Team = "DD", Opponent = "YUP2", Champion = "Anniva", Role = "MID", Kills = 0, Deaths = 3, Assists = 1 },
          new Player { PlayerId = 420, Summoner = "Epic-Gaymes", Team = "DD", Opponent = "INT2", Champion = "Jhin", Role = "ADC", Kills = 1, Deaths = 4, Assists = 3 }               
          );
    }
  }
}